Repository runtimeverification/k, pull requests merged in 2022-10, with the labels that each got.

#2924 Add M1 mac to CI
  .github/workflows/test-pr.yml
  flake.nix
Labels: automerge

#2948 Release nix on M1 mac
  .github/workflows/master-push.yml
Labels: automerge

#2949 Fix JQ error on M1 release CI
  .github/workflows/master-push.yml
Labels: automerge

#2940 GitHub action `test-package` for testing the Ubuntu packages
  .github/actions/test-package/action.yml
  .github/actions/with-docker/action.yml
  .github/workflows/Dockerfile
  .github/workflows/Dockerfile.maven-cache
  .github/workflows/Dockerfile.stack-deps
  .github/workflows/Dockerfile.z3
  .github/workflows/test-pr.yml
Labels: automerge

#2951 Add token to authenticate github API requests
  .github/workflows/master-push.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
Labels: automerge

#2936 Improve error handling in `k-util.sh`
  k-distribution/src/main/scripts/lib/k-util.sh
Labels: automerge

#2935 Move 'Nix flake submodule sync' to a separate workflow
  .github/workflows/test-pr.yml
  .github/workflows/update-deps.yml
Labels: automerge

#2955 Skip push of cachix action
  .github/workflows/master-push.yml
Labels: automerge

#2956 Move macro attribute from rules to syntax
  k-distribution/pl-tutorial/1_k/1_lambda/lesson_7/lambda.k
  k-distribution/pl-tutorial/1_k/1_lambda/lesson_8/lambda.k
  k-distribution/pl-tutorial/1_k/1_lambda/lesson_9/lambda.md
  k-distribution/pl-tutorial/1_k/3_lambda++/lesson_1/lambda.k
  k-distribution/pl-tutorial/1_k/3_lambda++/lesson_3/lambda.k
  k-distribution/pl-tutorial/1_k/3_lambda++/lesson_4/README.md
  k-distribution/pl-tutorial/1_k/3_lambda++/lesson_4/lambda.k
  k-distribution/pl-tutorial/1_k/3_lambda++/lesson_5/README.md
  k-distribution/pl-tutorial/1_k/3_lambda++/lesson_5/lambda.k
  k-distribution/pl-tutorial/1_k/3_lambda++/lesson_6/lambda.md
  k-distribution/pl-tutorial/1_k/5_types/lesson_1.9/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_2/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_3/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_4/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_5/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_6/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_7/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_8/README.md
  k-distribution/pl-tutorial/1_k/5_types/lesson_8/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_9.5/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_9/README.md
  k-distribution/pl-tutorial/1_k/5_types/lesson_9/lambda.k
  k-distribution/tests/regression-new/checks/checkMacroRecord.k
  k-distribution/tests/regression-new/checks/macroWithFunction.k
  k-distribution/tests/regression-new/checks/macroWithFunction.k.out
  k-distribution/tests/regression-new/checks/tokenCheck.k
Labels: automerge

#2952 Skip nix-maven step when possible
  .github/workflows/test-pr.yml
Labels: automerge

#2902 Print intermediate timing information about backend steps
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellBackend.java
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMBackend.java
Labels: automerge

#2957 `kup` improvements
  flake.lock
  flake.nix
  kup/poetry.lock
  kup/pyproject.toml
  kup/src/kup/__main__.py
Labels: automerge

#2922 Migrate Ubuntu packaging to GitHub workflows
  .github/workflows/release.yml
  Jenkinsfile
Labels: automerge, testing

#2846 pass --bound flag to llvm backend interpreter
  k-distribution/src/main/scripts/bin/krun
  k-distribution/tests/regression-new/search-bound/1.test
  k-distribution/tests/regression-new/search-bound/1.test.out
  k-distribution/tests/regression-new/search-bound/2.test
  k-distribution/tests/regression-new/search-bound/2.test.out
  k-distribution/tests/regression-new/search-bound/3.test
  k-distribution/tests/regression-new/search-bound/3.test.out
  k-distribution/tests/regression-new/search-bound/Makefile
  k-distribution/tests/regression-new/search-bound/test.k
Labels: automerge

#2961 2612 automatically add a ceil simplification rule for sets
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/tests/regression-new/ceil-set-generated/Makefile
  k-distribution/tests/regression-new/ceil-set-generated/ceil-set-cellSet-spec.k
  k-distribution/tests/regression-new/ceil-set-generated/ceil-set-cellSet-spec.k.out
  k-distribution/tests/regression-new/ceil-set-generated/ceil-set-regularSet-spec.k
  k-distribution/tests/regression-new/ceil-set-generated/ceil-set-regularSet-spec.k.out
  k-distribution/tests/regression-new/ceil-set-generated/ceil-set.k
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
Labels: automerge

#2965 Make `kup` throw an error if a nix command fails
  kup/src/kup/__main__.py
Labels: automerge

#2968 Fix quoting in IDs
  k-distribution/tests/regression-new/issue-2315-id-quotes/1.test
  k-distribution/tests/regression-new/issue-2315-id-quotes/1.test.out
  k-distribution/tests/regression-new/issue-2315-id-quotes/2.test
  k-distribution/tests/regression-new/issue-2315-id-quotes/2.test.out
  k-distribution/tests/regression-new/issue-2315-id-quotes/Makefile
  k-distribution/tests/regression-new/issue-2315-id-quotes/test.k
  kernel/src/main/java/org/kframework/compile/ConstantFolding.java
Labels: automerge

#2977 Bump nixpkgs
  flake.lock
Labels: automerge

#2979 Check if nix profile's `manifest.json` file exists
  kup/src/kup/__main__.py
Labels: automerge

#2980 Fix stale versions with `mvn package`
  kernel/pom.xml
Labels: automerge

#2975 Revert "2612 automatically add a ceil simplification rule for sets
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/tests/regression-new/ceil-set-generated/Makefile
  k-distribution/tests/regression-new/ceil-set-generated/ceil-set-cellSet-spec.k
  k-distribution/tests/regression-new/ceil-set-generated/ceil-set-cellSet-spec.k.out
  k-distribution/tests/regression-new/ceil-set-generated/ceil-set-regularSet-spec.k
  k-distribution/tests/regression-new/ceil-set-generated/ceil-set-regularSet-spec.k.out
  k-distribution/tests/regression-new/ceil-set-generated/ceil-set.k
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
Labels: automerge

#2959 Simplify several workflows procedure
  .github/workflows/master-push.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
  .github/workflows/update-deps.yml
Labels: automerge

#2973 Update release.yml
  .github/workflows/release.yml
Labels: automerge

#2985 Detach nix command in `kup`
  kup/src/kup/__main__.py
Labels: automerge

#2989 Add -v to packaged version string
  kernel/src/main/java/org/kframework/utils/file/JarInfo.java
Labels: automerge

#2986 Speculative fix for release workflow
  .github/workflows/release.yml
Labels: automerge

#2996 Add `--local` option to `kup`
  kup/src/kup/__main__.py
Labels: automerge

#2998 Anywhere is not supported by the haskell backend
  k-distribution/tests/regression-new/checkWarns/checkHaskellAnywhere.k
  k-distribution/tests/regression-new/checkWarns/checkHaskellAnywhere.k.out
  kernel/src/main/java/org/kframework/kompile/Kompile.java
Labels: automerge

#2992 Drop kompilex script
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMBackend.java
Labels: automerge

#2972 Relax module duplication check
  docs/user_manual.md
  k-distribution/tests/regression-new/checks/duplicateModule.k.out
  k-distribution/tests/regression-new/issue-2146-duplicateModules/test.k.out
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  kernel/src/main/java/org/kframework/kil/Module.java
  kernel/src/main/java/org/kframework/kore/convertors/KILtoKORE.java
  kernel/src/main/java/org/kframework/parser/ParserUtils.java
  kore/src/main/scala/org/kframework/attributes/Att.scala
Labels: automerge

#2971 Possible fix for colliding container names on start of new job
  .github/actions/test-package/action.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
Labels: automerge

#3007 Updates to documentation
  docs/ktools.md
  docs/user_manual.md
Labels: automerge

#3009 Adding commit sha to create uniq IDs for each build and avoid container collision
  .github/actions/test-package/action.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
Labels: automerge

#3001 Fix ubuntu releases
  .github/actions/test-package/action.yml
  .github/actions/with-docker/action.yml
  .github/workflows/Dockerfile
  .github/workflows/Dockerfile.maven-cache
  .github/workflows/Dockerfile.stack-deps
  .github/workflows/Dockerfile.z3
  .github/workflows/release.yml
  package/debian/compat.focal
  package/debian/rules.focal
Labels: automerge

#3006 V5.5.0 rc
  CHANGELOG.md
  install-k
  package/arch/PKGBUILD
  package/debian/changelog
  package/version
  src/main/scripts/test-in-container-debian
Labels: automerge

#3017 Activate triggers for when PR's are udpated,edited,reopened
  .github/workflows/test-pr.yml
Labels: automerge

#3013 Fix Ubuntu Focal Release
  .github/actions/test-package/action.yml
  .github/actions/with-docker/action.yml
  .github/workflows/Dockerfile
  .github/workflows/Dockerfile.maven-cache
  .github/workflows/Dockerfile.stack-deps
  .github/workflows/test-pr.yml
Labels: automerge

#3012 Add location info for KToken
  kore/src/main/scala/org/kframework/parser/TreeNodesToKORE.scala
Labels: bug, automerge

#3021 Add padding for start line
  kore/src/main/java/org/kframework/utils/errorsystem/KException.java
Labels: automerge

#3019 Fix the release process
  .github/workflows/release.yml
Labels: automerge

#3024 Remove `kup` and point the install script to the new kup repo
  .github/workflows/master-push.yml
  flake.lock
  flake.nix
  kup/.cruft.json
  kup/.flake8
  kup/.gitignore
  kup/Makefile
  kup/README.md
  kup/poetry.lock
  kup/pyproject.toml
  kup/src/kup/__init__.py
  kup/src/kup/__main__.py
  package/nix/install
Labels: automerge

#3011 doc: Fixed the iterate programming page
  web/build-html.js
Labels: automerge
