Repository runtimeverification/k, pull requests merged in 2022-07, with the labels that each got.

#2698 Calculate used variable names better in buildRule
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cterm.py
  pyk/src/pyk/integration_tests/test_configuration.py
  pyk/src/pyk/kastManip.py
  pyk/src/pyk/kcfg.py
  pyk/src/pyk/tests/test_kastManip.py
Labels: automerge

#2702 pyk/kprove: Make sure use_dir is Path.
  pyk/src/pyk/ktool/kprove.py
Labels: automerge

#2705 K tutorial wording improvements
  k-distribution/INSTALL.md
  k-distribution/k-tutorial/1_basic/02_basics/README.md
  k-distribution/k-tutorial/1_basic/03_parsing/README.md
  k-distribution/k-tutorial/1_basic/05_modules/README.md
  k-distribution/k-tutorial/1_basic/16_collections/README.md
  k-distribution/k-tutorial/1_basic/18_equality_and_conditionals/README.md
Labels: automerge

#2706 Pyk: Additional args for kompile, KProve has kompile named constructor.
  pyk/src/pyk/ktool/kompile.py
  pyk/src/pyk/tests/test_kompile.py
Labels: automerge, pyk

#2714 Kcfg print improvements, `#init` & `#target` aliases
  pyk/src/pyk/kastManip.py
  pyk/src/pyk/kcfg.py
  pyk/src/pyk/tests/test_kcfg.py
  pyk/src/pyk/utils.py
Labels: automerge

#2721 Downgrade Calibre to 5.42.0
  Dockerfile
Labels: automerge

#2723 Ci/milestone testing
  Jenkinsfile
Labels: automerge

#2725 KCFG: fix printing substitutions, Sort by nodes not node content
  pyk/src/pyk/cterm.py
  pyk/src/pyk/kast.py
  pyk/src/pyk/kcfg.py
  pyk/src/pyk/ktool/kprint.py
  pyk/src/pyk/tests/mock_kprint.py
  pyk/src/pyk/tests/test_kcfg.py
  pyk/src/pyk/tests/test_pretty_print_kast.py
  pyk/src/pyk/tests/test_subst.py
Labels: automerge, pyk

#2711 Forbid `[anywhere, simplification]` on rules
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/include/kframework/builtin/rat.md
  k-distribution/tests/regression-new/checks/anywhereSimplification.k
  k-distribution/tests/regression-new/checks/anywhereSimplification.k.out
  k-distribution/tests/regression-new/issue-2287-simpl-rules-in-kprovex/a2-spec.k
  k-distribution/tests/regression-new/issue-2287-simpl-rules-in-kprovex/a2-spec.k.out
  k-distribution/tests/regression-new/issue-2287-simpl-rules-in-kprovex/a3-spec.k
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  kernel/src/main/java/org/kframework/compile/checks/CheckAtt.java
  kernel/src/main/java/org/kframework/kompile/Kompile.java
Labels: automerge

#2710 Add warning for syntax priority / associativity mismatch
  USER_MANUAL.md
  k-distribution/k-tutorial/1_basic/04_disambiguation/README.md
  k-distribution/tests/regression-new/checkWarns/syntaxGroups.k
  k-distribution/tests/regression-new/checkWarns/syntaxGroups.k.out
  kernel/src/main/java/org/kframework/compile/checks/CheckSyntaxGroups.java
  kernel/src/main/java/org/kframework/kompile/Kompile.java
  kernel/src/main/java/org/kframework/kore/convertors/KILtoKORE.java
  kore/src/main/java/org/kframework/utils/errorsystem/KException.java
Labels: automerge

#2737 Fix trait RegexTerminalToString
  kore/src/main/scala/org/kframework/definition/outer-to-string.scala
Labels: bug, automerge

#2728 Fix method to_dict for some KAst subclasses
  pyk/k-files/regex-terminal.k
  pyk/src/pyk/integration_tests/kompiled_test.py
  pyk/src/pyk/integration_tests/test_regex_terminal.py
  pyk/src/pyk/kast.py
  pyk/src/pyk/ktool/kompile.py
  pyk/src/pyk/tests/test_kastManip.py
  pyk/src/pyk/tests/test_kompile.py
  pyk/src/pyk/utils.py
Labels: automerge, pyk

#2696 Add module pyk.kore
  pyk/src/pyk/kast.py
  pyk/src/pyk/kore/__init__.py
  pyk/src/pyk/kore/lexer.py
  pyk/src/pyk/kore/parser.py
  pyk/src/pyk/kore/syntax.py
  pyk/src/pyk/tests/kore/__init__.py
  pyk/src/pyk/tests/kore/json_data/withMultiThings_01.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_02.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_03.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_04.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_05.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_06.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_07.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_08.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_09.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_10.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_11.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_12.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_13.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_14.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_15.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_16.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_17.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_18.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_19.json
  pyk/src/pyk/tests/kore/json_data/withMultiThings_20.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_01.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_02.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_03.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_04.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_05.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_06.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_07.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_08.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_09.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_10.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_11.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_12.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_13.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_14.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_15.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_16.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_17.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_18.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_19.json
  pyk/src/pyk/tests/kore/json_data/withoutMultiThings_20.json
  pyk/src/pyk/tests/kore/test_identifiers.py
  pyk/src/pyk/tests/kore/test_lexer.py
  pyk/src/pyk/tests/kore/test_parser.py
  pyk/src/pyk/tests/kore/utils.py
  pyk/src/pyk/utils.py
Labels: automerge, pyk

#2729 Example project for `kompile --post-process` using `pyk`
  pyk/pyk-tests/Makefile
  pyk/pyk-tests/post-process/.gitignore
  pyk/pyk-tests/post-process/Makefile
  pyk/pyk-tests/post-process/assign.k
  pyk/pyk-tests/post-process/transform.py
Labels: automerge, pyk

#2743 Drop the tabulate dependency
  pyk/nix/overlay.nix
  pyk/nix/packages/pyk/default.nix
  pyk/nix/packages/tabulate/default.nix
  pyk/nix/packages/types-tabulate/default.nix
  pyk/requirements/base.txt
  pyk/setup.cfg
  pyk/src/pyk/ktool/kprove.py
Labels: automerge, pyk

#2741 Add Everett as a codeowner to /builtin
  CODEOWNERS
Labels: automerge

#2744 Add kore-rpc client
  pyk/src/pyk/kore/client.py
  pyk/src/pyk/tests/kore/test_client.py
Labels: automerge, pyk

#2738 Multipe modules in --emit-json-spec
  kernel/src/main/java/org/kframework/kprovex/KProve.java
  kernel/src/main/java/org/kframework/parser/json/JsonParser.java
  kernel/src/main/java/org/kframework/unparser/ToJson.java
  pyk/src/pyk/integration_tests/test_emit_json_spec.py
  pyk/src/pyk/kast.py
Labels: automerge

#2733 Func claims translation to KORE
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellRewriter.java
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
Labels: automerge

#2752 [nix] update pynixify in flake
  flake.lock
Labels: automerge

#2753 Include pyk in Focal package
  Jenkinsfile
  package/debian/Dockerfile
  package/debian/control.focal
  package/debian/rules
  package/docker/Dockerfile.ubuntu-focal
  package/package
  pyk/Makefile
  pyk/src/pyk/__main__.py
Labels: automerge

#2757 pyk/Makefile: remove --system argument to pip
  pyk/Makefile
Labels: automerge

#2751 Add back error for function simplification rules
  k-distribution/tests/regression-new/issue-2287-simpl-rules-in-kprovex/a2-spec.k
  k-distribution/tests/regression-new/issue-2287-simpl-rules-in-kprovex/a2-spec.k.out
  kernel/src/main/java/org/kframework/kompile/Kompile.java
Labels: automerge

#2756 Upstreaming pyk functionality
  pyk/Makefile
  pyk/src/pyk/integration_tests/test_defn.py
  pyk/src/pyk/kast.py
  pyk/src/pyk/kastManip.py
  pyk/src/pyk/kcfg.py
  pyk/src/pyk/ktool/kprint.py
  pyk/src/pyk/prelude.py
  pyk/src/pyk/tests/test_kast.py
  pyk/src/pyk/tests/test_kastManip.py
  pyk/src/pyk/tests/test_kcfg.py
  pyk/src/pyk/tests/test_pretty_print_kast.py
  pyk/src/pyk/tests/test_subst.py
Labels: automerge
