Repository runtimeverification/k, pull requests merged in 2023-10, with the labels that each got.

#3686 Builing MacOS Package on MacOS 13
  .github/workflows/release.yml
Labels: automerge, devops

#3683 Packaging: Move `version` into lib/kframework
  k-distribution/src/main/assembly/bin.xml
  kernel/src/main/java/org/kframework/utils/file/JarInfo.java
Labels: automerge

#3687 Introduces `--debugger-command` flag to krun
  k-distribution/src/main/scripts/bin/krun
Labels: automerge, llvm-backend

#3644 Updating `Guice` to 4.0 and deleting temporary injections
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellBackendKModule.java
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellKRunOptions.java
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellKompileOptions.java
  kernel/pom.xml
  kernel/src/main/java/org/kframework/kast/KastModule.java
  kernel/src/main/java/org/kframework/kast/KastOptions.java
  kernel/src/main/java/org/kframework/kdep/KDepModule.java
  kernel/src/main/java/org/kframework/kdep/KDepOptions.java
  kernel/src/main/java/org/kframework/kil/loader/Context.java
  kernel/src/main/java/org/kframework/kompile/BackendModule.java
  kernel/src/main/java/org/kframework/kompile/KompileModule.java
  kernel/src/main/java/org/kframework/kompile/KompileOptions.java
  kernel/src/main/java/org/kframework/kprove/KProveModule.java
  kernel/src/main/java/org/kframework/kprove/KProveOptions.java
  kernel/src/main/java/org/kframework/kprove/RewriterModule.java
  kernel/src/main/java/org/kframework/ksearchpattern/KSearchPatternModule.java
  kernel/src/main/java/org/kframework/ksearchpattern/KSearchPatternOptions.java
  kernel/src/main/java/org/kframework/kserver/KServerModule.java
  kernel/src/main/java/org/kframework/kserver/KServerOptions.java
  kernel/src/main/java/org/kframework/main/AbstractKModule.java
  kernel/src/main/java/org/kframework/main/FrontEnd.java
  kernel/src/main/java/org/kframework/main/GlobalOptions.java
  kernel/src/main/java/org/kframework/unparser/PrintOptions.java
  kernel/src/main/java/org/kframework/utils/inject/CommonModule.java
  kernel/src/main/java/org/kframework/utils/inject/DefinitionLoadingModule.java
  kernel/src/main/java/org/kframework/utils/inject/JCommanderModule.java
  kernel/src/main/java/org/kframework/utils/inject/OuterParsingModule.java
  kernel/src/main/java/org/kframework/utils/options/BackendOptions.java
  kernel/src/main/java/org/kframework/utils/options/DefinitionLoadingOptions.java
  kernel/src/main/java/org/kframework/utils/options/SMTOptions.java
  kernel/src/test/java/org/kframework/utils/BaseTestCase.java
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMKompileOptions.java
  nix/mavenix.lock
Labels: automerge, dependencies

#3660 kast --debug-tokens
  k-distribution/tests/regression-new/issue-3647-debugTokens/Makefile
  k-distribution/tests/regression-new/issue-3647-debugTokens/a.test.kast
  k-distribution/tests/regression-new/issue-3647-debugTokens/a.test.kast.out
  k-distribution/tests/regression-new/issue-3647-debugTokens/b.test.kast
  k-distribution/tests/regression-new/issue-3647-debugTokens/b.test.kast.out
  k-distribution/tests/regression-new/issue-3647-debugTokens/test.k
  kernel/src/main/java/org/kframework/kast/KastFrontEnd.java
  kernel/src/main/java/org/kframework/kast/KastOptions.java
  kernel/src/main/java/org/kframework/kompile/CompiledDefinition.java
  kernel/src/main/java/org/kframework/parser/KRead.java
  kernel/src/main/java/org/kframework/parser/inner/ParseInModule.java
  kernel/src/main/java/org/kframework/parser/inner/kernel/EarleyParser.java
  kernel/src/main/java/org/kframework/parser/inner/kernel/Scanner.java
Labels: automerge

#3691 Packaging: `version` path fix
  k-distribution/src/main/scripts/lib/k
  package/test-package
Labels: automerge

#3694 Use prebuilt z3 images
  .github/actions/with-docker/action.yml
  .github/workflows/Dockerfile
  .github/workflows/Dockerfile.z3
  deps/z3
Labels: automerge

#3696 Point to new `release.nix` upload action
  .github/workflows/release.yml
Labels: automerge

#3697 Use `macos-13` everywhere
  .github/workflows/release.yml
Labels: automerge

#3702 Use new Z3 image location
  .github/workflows/Dockerfile
Labels: automerge

#3703 Bump calibre version in release
  .github/workflows/release.yml
Labels: automerge

#3701 Move README from builtin
  k-distribution/include/kframework/README.md
  web/toc.md
Labels: automerge

#3709 Boost is a runtime dependency
  package/arch/PKGBUILD
Labels: automerge

#3714 Move dockerhub image to prebuilt z3
  package/debian/Dockerfile
  package/docker/Dockerfile.ubuntu-jammy
Labels: automerge

#3724 Rephrase `sed` invocation for macOS
  k-distribution/tests/regression-new/context-labels/Makefile
Labels: automerge

#3725 Drop mentions of Focal from packaging and install documentation
  README.md
  k-distribution/INSTALL.md
Labels: automerge

#3717 Move PL tutorial link out of main "learn K" section
  k-distribution/pl-tutorial/1_k/5_types/lesson_4/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_7/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_8/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_9.5/lambda.k
  k-distribution/pl-tutorial/1_k/5_types/lesson_9/lambda.k
  web/pages/index.md
Labels: automerge

#3734 Slimmer nix runtime closure
  flake.nix
  nix/k.nix
Labels: automerge

#3736 Bump JDK requirement to 17
  README.md
  package/debian/control.bookworm
  package/debian/control.jammy
  pom.xml
Labels: automerge

#3722 Support for memset hook.
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/tests/regression-new/bytes-memset/1.test
  k-distribution/tests/regression-new/bytes-memset/1.test.out
  k-distribution/tests/regression-new/bytes-memset/2.test
  k-distribution/tests/regression-new/bytes-memset/2.test.out
  k-distribution/tests/regression-new/bytes-memset/Makefile
  k-distribution/tests/regression-new/bytes-memset/test.k
Labels: automerge

#3733 Add `lowerBounds` and `upperBounds` methods to `POSet`
  kernel/src/main/java/org/kframework/compile/AddSortInjections.java
  kore/src/main/scala/org/kframework/POSet.scala
  kore/src/test/scala/org/kframework/POSetTest.scala
Labels: automerge

#3700 Add option to print better parse errors
  k-distribution/tests/regression-new/issue-3672-debugParse/Makefile
  k-distribution/tests/regression-new/issue-3672-debugParse/a.test.kast
  k-distribution/tests/regression-new/issue-3672-debugParse/a.test.kast.out
  k-distribution/tests/regression-new/issue-3672-debugParse/b.test.kast
  k-distribution/tests/regression-new/issue-3672-debugParse/b.test.kast.out
  k-distribution/tests/regression-new/issue-3672-debugParse/test.k
  kernel/src/main/java/org/kframework/kast/KastFrontEnd.java
  kernel/src/main/java/org/kframework/kast/KastOptions.java
  kernel/src/main/java/org/kframework/kompile/CompiledDefinition.java
  kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java
  kernel/src/main/java/org/kframework/parser/KRead.java
  kernel/src/main/java/org/kframework/parser/inner/ParseInModule.java
  kernel/src/main/java/org/kframework/parser/inner/RuleGrammarGenerator.java
  kernel/src/main/java/org/kframework/parser/inner/kernel/EarleyParser.java
Labels: automerge

#3741 Fix for macOS nix / kup breakage
  .github/workflows/test-pr.yml
  flake.nix
  nix/k.nix
Labels: automerge

#3742 Fix release by installing Calibre 6
  .github/workflows/release.yml
Labels: automerge

#3743 Check for Java 17 when running K tools
  k-distribution/src/main/scripts/lib/checkJava
Labels: automerge

#3745 Apply Java 17 automatic migration: enhanced switch
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  kernel/src/main/java/org/kframework/compile/ConstantFolding.java
  kernel/src/main/java/org/kframework/kast/KastFrontEnd.java
  kernel/src/main/java/org/kframework/kil/StringSentence.java
  kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java
  kernel/src/main/java/org/kframework/kore/convertors/KILtoKORE.java
  kernel/src/main/java/org/kframework/lsp/TextDocumentSyncHandler.java
  kernel/src/main/java/org/kframework/parser/KRead.java
  kernel/src/main/java/org/kframework/parser/inner/disambiguation/TypeInferenceVisitor.java
  kernel/src/main/java/org/kframework/parser/inner/disambiguation/TypeInferencer.java
  kernel/src/main/java/org/kframework/parser/json/JsonParser.java
  kernel/src/main/java/org/kframework/unparser/Formatter.java
  kernel/src/main/java/org/kframework/unparser/KPrint.java
  kernel/src/main/java/org/kframework/utils/ColorUtil.java
  kernel/src/main/java/org/kframework/utils/options/DurationConverter.java
  kernel/src/test/java/org/kframework/unparser/KPrintTest.java
  kore/src/main/java/org/kframework/compile/ConfigurationInfo.java
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMBackend.java
Labels: automerge

#3749 Revert to nix-community/mavenix in nix build
  flake.lock
  flake.nix
  nix/k.nix
Labels: automerge

#3748 Update nix install script
  package/nix/install
Labels: automerge

#3754 Pin nixpkgs to haskell-backend
  flake.lock
  flake.nix
Labels: automerge

#3760 Temporary hotfixes for release flakiness
  .github/workflows/release.yml
Labels: automerge

#3761 Update README instructions
  README.md
Labels: automerge

#3764 Move mac release CI to hosted ARM runners
  .github/workflows/release.yml
Labels: automerge

#3766 Install wget in release job
  .github/workflows/release.yml
Labels: automerge

#3768 Clean up Homebrew after running commands
  .github/workflows/release.yml
Labels: automerge

#3765 Drop Arch Linux and Debian packaging
  .github/workflows/release.yml
  README.md
  install-k
  k-distribution/INSTALL.md
  package/arch/Dockerfile
  package/arch/Dockerfile.maven-cache
  package/arch/Dockerfile.stack-deps
  package/arch/Dockerfile.z3
  package/arch/PKGBUILD
  package/arch/build-package
  package/arch/test-package
  package/debian/compat.bookworm
  package/debian/control.bookworm
  package/debian/rules
  package/debian/rules.bookworm
  package/version.sh
Labels: automerge

#3770 Temporary restore of arch PKGBUILD
  package/arch/PKGBUILD
Labels: automerge

#3771 Revert experimental Homebrew changes
  .github/workflows/release.yml
Labels: automerge

#3772 Fix release cachix action
  .github/workflows/release.yml
Labels: automerge

#3774 Update README to address missing dependency
  README.md
Labels: automerge

#3776 Move homebrew mentions to new repository
  .github/workflows/release.yml
  k-distribution/INSTALL.md
  package/macos/brew-build-and-update-to-local-bottle
  package/macos/brew-install-bottle
Labels: automerge

#3773 Finally remove PKGBUILD
  package/arch/PKGBUILD
Labels: automerge

#3778 Update release.yml
  .github/workflows/release.yml
Labels: automerge

#3779 Revert #3773
  package/arch/PKGBUILD
Labels: automerge
