Repository runtimeverification/k, pull requests merged in 2023-03, with the labels that each got.

#3201 Fix Nix upgrade breaking cachix
  .github/workflows/master-push.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
  .github/workflows/update-deps.yml
Labels: automerge

#3194 Add K-Javalette
  web/pages/projects.md
Labels: automerge

#3197 Update deps GH workflow
  .github/workflows/release.yml
Labels: automerge

#3196 Add new flag '--no-pattern' to krun to skip kore-match-disjunction
  k-distribution/src/main/scripts/bin/krun
  k-distribution/tests/regression-new/no-pattern/1.test
  k-distribution/tests/regression-new/no-pattern/1.test.out
  k-distribution/tests/regression-new/no-pattern/Makefile
  k-distribution/tests/regression-new/no-pattern/test.k
Labels: automerge, frontend

#3207 Add flag to enable LLVM backend debugging
  docs/cheat_sheet.md
  docs/ktools.md
  k-distribution/k-tutorial/1_basic/19_debugging/README.md
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMBackend.java
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMKompileOptions.java
Labels: automerge

#3205 Updating cachix references for building ghc
  .github/workflows/master-push.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
  .github/workflows/update-deps.yml
Labels: automerge

#3206 make K work with Java 19
  kernel/src/main/java/org/kframework/main/Main.java
  kernel/src/main/java/org/kframework/parser/ParserUtils.java
  kernel/src/main/java/org/kframework/utils/ExitOnTimeoutThread.java
Labels: automerge

#3195 Tut fix typofix addedlink
  k-distribution/k-tutorial/1_basic/03_parsing/README.md
  k-distribution/k-tutorial/1_basic/19_debugging/README.md
Labels: automerge, documentation, tutorial, web

#3215 Updated README to add fmt as an install prerequisite
  README.md
Labels: automerge, documentation

#3217 Fixes for mac install of kup
  package/nix/install
Labels: automerge

#3213 disable some modules in the maude backend for the time being
  k-distribution/include/kframework/builtin/domains.md
Labels: automerge

#3212 Change invocation of `lldb`
  k-distribution/src/main/scripts/bin/krun
Labels: automerge

#3230 Automatically use `--no-haskell-binary` in macOS regression tests
  flake.nix
  k-distribution/include/kframework/ktest.mak
  k-distribution/tests/regression-new/help/check-git-revision-format
Labels: automerge

#3238 Add g++ to dependencies on debian systems
  Dockerfile
  README.md
  package/debian/Dockerfile
  package/debian/control.bullseye
  package/debian/control.focal
  package/debian/control.jammy
Labels: automerge

#3239 Workflow/enable community workflow checks
  .github/workflows/test-pr.yml
Labels: automerge

#3249 Write external contributors document
  CONTRIBUTING.md
  LICENSE.md
Labels: automerge

#3248 Adopt #3192 for CI
  k-distribution/include/kframework/builtin/domains.md
Labels: automerge

#3229 Update documentation for new LLDB support
  docs/cheat_sheet.md
  docs/ktools.md
  k-distribution/k-tutorial/1_basic/19_debugging/README.md
  k-distribution/src/main/scripts/bin/krun
  web/toc.md
Labels: automerge

#3261 V5.6.0 rc
  CHANGELOG.md
  install-k
  package/arch/PKGBUILD
  package/debian/changelog
  package/version
Labels: automerge

#3263 Add error message for empty Map collections
  k-distribution/tests/regression-new/checks/emptyMapCollection.k
  k-distribution/tests/regression-new/checks/emptyMapCollection.k.out
  kernel/src/main/java/org/kframework/compile/GenerateSentencesFromConfigDecl.java
Labels: automerge, error-message

#3270 Replacing llvm 14 with llvm 15 as a pre-requirement for K
  README.md
  k-distribution/k-tutorial/1_basic/19_debugging/README.md
  macos-envrc
Labels: automerge, apple-silicon

#3272 Install C binding headers in Nix
  nix/k.nix
Labels: automerge

#3275 Re-export kore-rpc server with K
  nix/k.nix
Labels: automerge

#3279 Drop `kprove-legacy`
  k-distribution/include/kframework/ktest.mak
  k-distribution/src/main/scripts/bin/kprove-legacy
  k-distribution/tests/regression-new/checkClaimError/Makefile
  k-distribution/tests/regression-new/checkWarnsClaim/Makefile
  k-distribution/tests/regression-new/checkWarnsClaim/warnClaim-spec.k
  k-distribution/tests/regression-new/checkWarnsClaim/warnClaim-spec.k.out
  k-distribution/tests/regression-new/checkWarnsClaim/warnClaim.k
  k-distribution/tests/regression-new/concrete-function-cache/Makefile
  k-distribution/tests/regression-new/concrete-function/Makefile
  k-distribution/tests/regression-new/concrete-haskell/Makefile
  k-distribution/tests/regression-new/domains-lemmas-no-smt/Makefile
  k-distribution/tests/regression-new/domains-lemmas-smt/Makefile
  k-distribution/tests/regression-new/help/Makefile
  k-distribution/tests/regression-new/imp-haskell/Makefile
  k-distribution/tests/regression-new/issue-1471-proofSyntaxWarning/Makefile
  k-distribution/tests/regression-new/issue-1471-proofSyntaxWarning/proofSyntax-spec.k
  k-distribution/tests/regression-new/issue-1471-proofSyntaxWarning/proofSyntax-spec.k.out
  k-distribution/tests/regression-new/issue-1471-proofSyntaxWarning/proofSyntax.k
  k-distribution/tests/regression-new/issue-2142-markConcrete/Makefile
  k-distribution/tests/regression-new/issue-2174-kprovexParseError/Makefile
  k-distribution/tests/regression-new/issue-2287-simpl-rules-in-kprovex/Makefile
  k-distribution/tests/regression-new/issue-2321-kprovexCrash/Makefile
  k-distribution/tests/regression-new/issue-2812-kprove-filter-claims/claims/Makefile
  k-distribution/tests/regression-new/issue-2812-kprove-filter-claims/exclude/Makefile
  k-distribution/tests/regression-new/issue-2812-kprove-filter-claims/trusted/Makefile
  k-distribution/tests/regression-new/itp/nat-assoc/Makefile
  k-distribution/tests/regression-new/itp/nat-assoc/assoc-spec.k
  k-distribution/tests/regression-new/itp/nat-assoc/nat.k
  k-distribution/tests/regression-new/itp/nth-ancestor/Makefile
  k-distribution/tests/regression-new/itp/nth-ancestor/haskell/Makefile
  k-distribution/tests/regression-new/itp/nth-ancestor/haskell/chain.k
  k-distribution/tests/regression-new/itp/nth-ancestor/haskell/proof-script.k
  k-distribution/tests/regression-new/itp/nth-ancestor/nth2-spec.k
  k-distribution/tests/regression-new/itp/nth-ancestor/verification.k
  k-distribution/tests/regression-new/kprove-error-status/Makefile
  k-distribution/tests/regression-new/kprove-java/Makefile
  k-distribution/tests/regression-new/kprove-macro-exp-productions/Makefile
  k-distribution/tests/regression-new/kprove-macro-exp/Makefile
  k-distribution/tests/regression-new/kprove-markdown/Makefile
  k-distribution/tests/regression-new/kprove-markdown/set-balance-spec.md
  k-distribution/tests/regression-new/kprove-markdown/verification.k
  k-distribution/tests/regression-new/map-symbolic-tests-haskell/Makefile
  k-distribution/tests/regression-new/markdownSelectors/Makefile
  k-distribution/tests/regression-new/profile/Makefile
  k-distribution/tests/regression-new/set-symbolic-tests/Makefile
  kernel/src/main/java/org/kframework/kserver/KServerFrontEnd.java
  kernel/src/main/java/org/kframework/main/Main.java
  test.nix
Labels: automerge

#3282 Add timeouts to release job
  .github/workflows/release.yml
Labels: automerge

#3287 Add warning messages when kompiled def is missing
  kernel/src/main/java/org/kframework/lsp/TextDocumentSyncHandler.java
Labels: automerge

#3151 Add codeowners for version file
  CODEOWNERS
Labels: automerge

#3288 Deleting axiom production when the it doesn't have any terms.
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
Labels: bug, automerge

#3292 Improve lesson 1_08 exercise 2 to point to the source README.md
  k-distribution/k-tutorial/1_basic/08_literate_programming/README.md
Labels: automerge, documentation
