Repository runtimeverification/k, pull requests merged in 2023-09, with the labels that each got.

#3615 Fix token constructor error
  k-distribution/tests/regression-new/checks/tokenCheck.k
  k-distribution/tests/regression-new/checks/tokenCheck.k.out
  kernel/src/main/java/org/kframework/compile/checks/CheckTokens.java
  kore/src/main/scala/org/kframework/definition/outer.scala
Labels: automerge

#3617 Update Lesson 1.2 to point to the correct further lesson/link
  k-distribution/k-tutorial/1_basic/02_basics/README.md
Labels: automerge, tutorial

#3622 Revert "Ordering instance for Sentences"
  k-distribution/tests/builtins/collections/test-set2list-2.col.out
  k-distribution/tests/builtins/collections/test-set2list-3.col.out
  kore/src/main/scala/org/kframework/attributes/Att.scala
  kore/src/main/scala/org/kframework/definition/outer.scala
  kore/src/test/scala/org/kframework/definition/OuterTest.scala
Labels: automerge

#3618 Improving Lesson 1.3 by mentioning longest match while scanning tokens
  k-distribution/k-tutorial/1_basic/03_parsing/README.md
Labels: automerge, tutorial

#3623 Update `krun` usage message to contain `[options]`
  k-distribution/src/main/scripts/bin/krun
Labels: automerge

#3626 Fix k script to print `--version` correctly in docker container
  k-distribution/src/main/scripts/lib/k
Labels: automerge, frontend

#3631 Add K-ST
  web/pages/projects.md
Labels: automerge

#3636 Fix parsing left/right-assoc kore terms in kast
  kore/src/main/scala/org/kframework/parser/kore/parser/TextToKore.scala
  kore/src/test/scala/org/kframework/parser/kore/parser/TextToKoreTest.scala
Labels: automerge

#3637 Installing dependences to bencher execution on develop
  .github/workflows/develop.yml
  k-distribution/tests/profiling/setup_profiling.sh
Labels: automerge, devops

#3638 Improving kompile's `--help` and `--help-hidden` messages using descriptors
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellKompileOptions.java
  k-distribution/src/main/scripts/lib/k-util.sh
  kernel/src/main/java/org/kframework/kompile/KompileOptions.java
  kernel/src/main/java/org/kframework/kompile/KompileUsageFormatter.java
  kernel/src/main/java/org/kframework/main/GlobalOptions.java
  kernel/src/main/java/org/kframework/utils/options/InnerParsingOptions.java
  kernel/src/main/java/org/kframework/utils/options/OuterParsingOptions.java
  kernel/src/main/java/org/kframework/utils/options/OutputDirectoryOptions.java
  kernel/src/main/java/org/kframework/utils/options/SMTOptions.java
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMKompileOptions.java
Labels: automerge, frontend

#3642 Adding arguments to `kast` flags
  kernel/src/main/java/org/kframework/kast/KastOptions.java
  kernel/src/main/java/org/kframework/unparser/PrintOptions.java
  kernel/src/main/java/org/kframework/utils/options/DefinitionLoadingOptions.java
Labels: automerge, frontend

#3639 docs: :memo: Added section 2 docs
  web/toc.md
Labels: automerge

#3648 Adding arguments to `kprove` flags
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellKRunOptions.java
  kernel/src/main/java/org/kframework/kast/KastOptions.java
  kernel/src/main/java/org/kframework/kompile/KompileOptions.java
  kernel/src/main/java/org/kframework/kprove/KProveOptions.java
  kernel/src/main/java/org/kframework/utils/options/OutputDirectoryOptions.java
  kernel/src/main/java/org/kframework/utils/options/SMTOptions.java
Labels: automerge, frontend

#3649 Fix K Version on Debian
  k-distribution/src/main/scripts/lib/k
Labels: automerge, frontend

#3652 Clean up flake inputs
  flake.nix
Labels: automerge

#3653 Fix output sorting for KPrint
  kernel/src/main/java/org/kframework/unparser/KPrint.java
Labels: automerge

#3655 Fixing `develop.yml` workflow
  .github/workflows/develop.yml
  k-distribution/tests/profiling/post_results_to_develop.py
Labels: automerge, devops

#3658 Setting $workspace variable in `develop.yml`
  .github/workflows/develop.yml
Labels: automerge, devops

#3654 Refactor GeneratedTopFormat
  k-distribution/tests/regression-new/issue-3604-counterCell/1.test
  k-distribution/tests/regression-new/issue-3604-counterCell/1.test.out
  k-distribution/tests/regression-new/issue-3604-counterCell/Makefile
  k-distribution/tests/regression-new/issue-3604-counterCell/test.k
  kernel/src/main/java/org/kframework/backend/kore/KoreBackend.java
  kernel/src/main/java/org/kframework/compile/GeneratedTopFormat.java
  kernel/src/main/java/org/kframework/compile/ResolveFreshConstants.java
Labels: automerge

#3664 Updating Maven and Testing it
  nix/mavenix.lock
  pom.xml
Labels: automerge, dependencies

#3662 Check if macros were expanded in `ensures` and `requires`
  k-distribution/tests/regression-new/checks/expandMacroEnsures.k
  k-distribution/tests/regression-new/checks/expandMacroEnsures.k.out
  k-distribution/tests/regression-new/checks/expandMacroRequires.k
  k-distribution/tests/regression-new/checks/expandMacroRequires.k.out
  kernel/src/main/java/org/kframework/compile/ExpandMacros.java
Labels: automerge, kompile

#3659 Add llvm-kompile-matching to K package
  k-distribution/src/main/assembly/bin.xml
  llvm-backend/src/main/scripts/bin/llvm-kompile-matching
  llvm-backend/src/main/scripts/lib/llvm-backend
Labels: automerge

#3665 remove build extension for aws s3 that is no longer used
  nix/mavenix.lock
  pom.xml
Labels: automerge

#3670 Ordering instance for Sentences (2)
  k-distribution/tests/builtins/collections/test-set2list-2.col.out
  k-distribution/tests/builtins/collections/test-set2list-3.col.out
  kore/src/main/scala/org/kframework/attributes/Att.scala
  kore/src/main/scala/org/kframework/definition/outer.scala
  kore/src/test/scala/org/kframework/definition/OuterTest.scala
Labels: automerge
