Repository runtimeverification/k, pull requests merged in 2023-05, with the labels that each got.

#3375 Fix GeneratedCounterCell location
  kernel/src/main/java/org/kframework/backend/kore/KoreBackend.java
  kernel/src/main/java/org/kframework/compile/GeneratedTopFormat.java
  kernel/src/main/java/org/kframework/compile/ResolveFreshConstants.java
Labels: automerge

#3371 Add UniqueId to all sentences, including generated ones
  kernel/src/main/java/org/kframework/backend/kore/KoreBackend.java
Labels: automerge

#3364 Updating mint-llvm Makefile and test from Haskell to LLVM Backend
  k-distribution/tests/regression-new/mint-llvm/1.test
  k-distribution/tests/regression-new/mint-llvm/1.test.out
  k-distribution/tests/regression-new/mint-llvm/10.test
  k-distribution/tests/regression-new/mint-llvm/10.test.out
  k-distribution/tests/regression-new/mint-llvm/11.test
  k-distribution/tests/regression-new/mint-llvm/11.test.out
  k-distribution/tests/regression-new/mint-llvm/12.test
  k-distribution/tests/regression-new/mint-llvm/12.test.out
  k-distribution/tests/regression-new/mint-llvm/13.test
  k-distribution/tests/regression-new/mint-llvm/13.test.out
  k-distribution/tests/regression-new/mint-llvm/14.test
  k-distribution/tests/regression-new/mint-llvm/14.test.out
  k-distribution/tests/regression-new/mint-llvm/15.test
  k-distribution/tests/regression-new/mint-llvm/15.test.out
  k-distribution/tests/regression-new/mint-llvm/16.test
  k-distribution/tests/regression-new/mint-llvm/16.test.out
  k-distribution/tests/regression-new/mint-llvm/17.test
  k-distribution/tests/regression-new/mint-llvm/17.test.out
  k-distribution/tests/regression-new/mint-llvm/18.test
  k-distribution/tests/regression-new/mint-llvm/18.test.out
  k-distribution/tests/regression-new/mint-llvm/2.test
  k-distribution/tests/regression-new/mint-llvm/2.test.out
  k-distribution/tests/regression-new/mint-llvm/3.test
  k-distribution/tests/regression-new/mint-llvm/3.test.out
  k-distribution/tests/regression-new/mint-llvm/4.test
  k-distribution/tests/regression-new/mint-llvm/4.test.out
  k-distribution/tests/regression-new/mint-llvm/5.test
  k-distribution/tests/regression-new/mint-llvm/5.test.out
  k-distribution/tests/regression-new/mint-llvm/6.test
  k-distribution/tests/regression-new/mint-llvm/6.test.out
  k-distribution/tests/regression-new/mint-llvm/7.test
  k-distribution/tests/regression-new/mint-llvm/7.test.out
  k-distribution/tests/regression-new/mint-llvm/8.test
  k-distribution/tests/regression-new/mint-llvm/8.test.out
  k-distribution/tests/regression-new/mint-llvm/9.test
  k-distribution/tests/regression-new/mint-llvm/9.test.out
  k-distribution/tests/regression-new/mint-llvm/Makefile
  k-distribution/tests/regression-new/mint-llvm/test.k
Labels: automerge, testing

#3391 Make new-format rules without antileft the default
  k-distribution/tests/regression-new/issue-3035-antileft/haskell/Makefile
  k-distribution/tests/regression-new/issue-3035-antileft/llvm/Makefile
  k-distribution/tests/regression-new/map-symbolic-tests-haskell/assignment-11-spec.k.out
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  kernel/src/main/java/org/kframework/kompile/KompileOptions.java
Labels: automerge

#3395 Update missing KLabel checks to stabilize error messages
  k-distribution/tests/regression-new/checkWarns/missingKlabel.k
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
Labels: automerge

#3354 Total attribute is allowed only on function symbols
  k-distribution/tests/regression-new/checks/totalWithoutFunction.k
  k-distribution/tests/regression-new/checks/totalWithoutFunction.k.out
  kernel/src/main/java/org/kframework/compile/checks/CheckAtt.java
Labels: automerge

#3400 Setting `--directory` as deprecated
  k-distribution/include/kframework/ktest-fail.mak
  k-distribution/include/kframework/ktest.mak
  k-distribution/src/main/scripts/bin/kore-print
  k-distribution/src/main/scripts/bin/kparse
  k-distribution/src/main/scripts/bin/kparse-gen
  k-distribution/src/main/scripts/bin/krun
  k-distribution/tests/regression-new/bad-flags/Makefile
  k-distribution/tests/regression-new/cell-bag-sort-llvm/Makefile
  k-distribution/tests/regression-new/concrete-function-cache/Makefile
  k-distribution/tests/regression-new/concrete-function/Makefile
  k-distribution/tests/regression-new/issue-1489-claimLoc/Makefile
  k-distribution/tests/regression-new/issue-1683-cfgVarsWarns/Makefile
  k-distribution/tests/regression-new/issue-2146-duplicateModules/Makefile
  k-distribution/tests/regression-new/issue-2273/Makefile
  k-distribution/tests/regression-new/issue-946/Makefile
  k-distribution/tests/regression-new/ite-bug/Makefile
  k-distribution/tests/regression-new/parseKORE2/Makefile
  kernel/src/main/java/org/kframework/utils/inject/DefinitionLoadingModule.java
  kernel/src/main/java/org/kframework/utils/inject/OuterParsingModule.java
  kernel/src/main/java/org/kframework/utils/options/DefinitionLoadingOptions.java
  kernel/src/main/java/org/kframework/utils/options/OutputDirectoryOptions.java
  kore/src/main/java/org/kframework/utils/errorsystem/KException.java
Labels: enhancement, automerge

#3409 Update `make clean` to account for a few missed test artifacts
  k-distribution/include/kframework/ktest.mak
  k-distribution/tests/regression-new/issue-1169/Makefile
Labels: automerge

#3414 Replacing deprecated option flag at tutorial tests
  k-distribution/k-tutorial/1_basic/commands.sh
  k-distribution/k-tutorial/2_intermediate/commands.sh
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_1/Makefile
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_6/Makefile
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_7/Makefile.concrete
  k-distribution/pl-tutorial/2_languages/1_simple/1_untyped/Makefile
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/2_dynamic/Makefile
  k-distribution/pl-tutorial/2_languages/2_kool/2_typed/2_static/Makefile
  k-distribution/pl-tutorial/2_languages/3_fun/1_untyped/1_environment/Makefile
  k-distribution/pl-tutorial/2_languages/3_fun/1_untyped/1_environment/exercises/io/Makefile
  k-distribution/pl-tutorial/2_languages/4_logik/basic/Makefile
  k-distribution/tests/regression-new/kdep-options/remake-depend/Makefile
  k-distribution/tests/regression-new/kdep-options/simple/Makefile
  kernel/src/main/java/org/kframework/kdep/KDepFrontEnd.java
Labels: automerge, testing

#3412 Restrict `Bytes` token syntax
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/tests/regression-new/bad-bytes-literal/Makefile
  k-distribution/tests/regression-new/bad-bytes-literal/quote.k
  k-distribution/tests/regression-new/bad-bytes-literal/quote.k.out
  k-distribution/tests/regression-new/bad-bytes-literal/slash.k
  k-distribution/tests/regression-new/bad-bytes-literal/slash.k.out
  k-distribution/tests/regression-new/bad-bytes-literal/unicode-escape.k
  k-distribution/tests/regression-new/bad-bytes-literal/unicode-escape.k.out
  k-distribution/tests/regression-new/bad-bytes-literal/unicode.k
  k-distribution/tests/regression-new/bad-bytes-literal/unicode.k.out
  k-distribution/tests/regression-new/bytes-literal/1.test
  k-distribution/tests/regression-new/bytes-literal/1.test.out
  k-distribution/tests/regression-new/bytes-literal/2.test
  k-distribution/tests/regression-new/bytes-literal/2.test.out
  k-distribution/tests/regression-new/bytes-literal/test.k
Labels: automerge

#3401 Fixing Kore label munging confusion
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  kore/src/main/java/org/kframework/utils/StringUtil.java
  kore/src/main/scala/org/kframework/parser/kore/parser/KoreToK.scala
Labels: automerge, module-to-kore

#3419 Remove dead code HaskellKRunOptions
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellBackendKModule.java
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellKRunOptions.java
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellRewriter.java
  kernel/src/main/java/org/kframework/main/AbstractKModule.java
  kernel/src/main/java/org/kframework/main/KModule.java
Labels: automerge

#3407 Introduces `--execute-to-branch` to `krun` when using LLVM Backend
  k-distribution/src/main/scripts/bin/krun
Labels: enhancement, automerge, llvm-backend

#3420 Pretty print NonTerminal names in generated txt files
  kore/src/main/scala/org/kframework/definition/outer-to-string.scala
Labels: automerge

#3424 Revert "Remove dead code HaskellKRunOptions"
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellBackendKModule.java
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellKRunOptions.java
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellRewriter.java
  kernel/src/main/java/org/kframework/main/AbstractKModule.java
  kernel/src/main/java/org/kframework/main/KModule.java
Labels: automerge

#3430 Improving kore-print script
  k-distribution/src/main/scripts/bin/kore-print
  k-distribution/src/main/scripts/bin/kparse
  k-distribution/src/main/scripts/bin/kparse-gen
  k-distribution/src/main/scripts/bin/krun
  k-distribution/src/main/scripts/lib/k-util.sh
Labels: enhancement, automerge

#3431 Update projects description
  web/pages/index.md
  web/pages/projects.md
Labels: automerge

#3434 Fix error message when missing sort
  k-distribution/tests/regression-new/checks/noImportFloat.k
  k-distribution/tests/regression-new/checks/noImportFloat.k.out
  kore/src/main/scala/org/kframework/definition/outer.scala
Labels: automerge

#3437 Check that sorts are well-formed for left, right, and non-assoc productions
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/include/kframework/builtin/rat.md
  k-distribution/tests/regression-new/checks/checkAssoc.k
  k-distribution/tests/regression-new/checks/checkAssoc.k.out
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  kernel/src/main/java/org/kframework/compile/checks/CheckAssoc.java
  kernel/src/main/java/org/kframework/kompile/Kompile.java
  kernel/src/main/java/org/kframework/kore/convertors/KILtoKORE.java
  kore/src/main/scala/org/kframework/attributes/Att.scala
Labels: automerge, attributes

#3432 Implementing support for pretty printing non-terminals name
  k-distribution/tests/regression-new/issue-1263/1.test.out
  k-distribution/tests/regression-new/pattern-macro-productions/3.test.out
  k-distribution/tests/regression-new/pattern-macro/3.test.out
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
Labels: enhancement, automerge
