Repository runtimeverification/k, pull requests merged in 2023-07, with the labels that each got.

#3484 Ensure module attributes are checked against the whitelist
  k-distribution/k-tutorial/1_basic/05_modules/README.md
  k-distribution/tests/regression-new/checks/checkModuleAtts.k
  k-distribution/tests/regression-new/checks/checkModuleAtts.k.out
  kernel/src/main/java/org/kframework/compile/ProcessGroupAttributes.java
  kernel/src/main/java/org/kframework/compile/checks/CheckAtt.java
  kernel/src/main/java/org/kframework/kompile/Kompile.java
  kore/src/main/scala/org/kframework/attributes/Att.scala
Labels: automerge, attributes

#3441 Emit user-defined groups as group(_)
  k-distribution/tests/regression-new/checks/checkGroup.k.out
  k-distribution/tests/regression-new/group/test.k
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  kernel/src/main/java/org/kframework/compile/GenerateSentencesFromConfigDecl.java
  kernel/src/main/java/org/kframework/compile/ProcessGroupAttributes.java
  kernel/src/main/java/org/kframework/parser/json/JsonParser.java
  kernel/src/main/java/org/kframework/unparser/ToJson.java
  kore/src/main/scala/org/kframework/attributes/Att.scala
Labels: automerge, attributes

#3489 Ensure that non-ASCII characters are escaped when emitting to KORE
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  kore/src/main/java/org/kframework/utils/StringUtil.java
Labels: automerge

#3487 Update documentation and tutorials for `group(_)`
  docs/user_manual.md
  k-distribution/k-tutorial/1_basic/04_disambiguation/README.md
  k-distribution/k-tutorial/1_basic/11_casts/README.md
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_8/imp.md
  k-distribution/pl-tutorial/2_languages/1_simple/1_untyped/simple-untyped.md
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/1_static/simple-typed-static.md
  k-distribution/pl-tutorial/2_languages/3_fun/1_untyped/1_environment/fun-untyped.md
Labels: automerge, attributes

#3497 Correctly escape ASCII values in the range 0-31
  kore/src/main/java/org/kframework/utils/StringUtil.java
Labels: automerge

#3503 .github/workflows/update-deps: sync up booster release tag too
  .github/workflows/update-deps.yml
  deps/hs-backend-booster_release
  flake.lock
  flake.nix
Labels: automerge

#3507 JSON creation - use object factory
  kernel/src/main/java/org/kframework/kompile/Kompile.java
  kernel/src/main/java/org/kframework/unparser/ToJson.java
Labels: automerge

#3499 Remove the option to opt out of the attribute whitelist
  k-distribution/src/test/java/org/kframework/kore/convertors/BaseTest.java
  k-distribution/src/test/java/org/kframework/kore/convertors/TstKILtoKOREIT.java
  k-distribution/tests/regression-new/issue-1169/Makefile
  kernel/src/main/java/org/kframework/backend/kore/KoreBackend.java
  kernel/src/main/java/org/kframework/compile/GenerateSentencesFromConfigDecl.java
  kernel/src/main/java/org/kframework/compile/ProcessGroupAttributes.java
  kernel/src/main/java/org/kframework/compile/ResolveFreshConstants.java
  kernel/src/main/java/org/kframework/compile/checks/CheckAtt.java
  kernel/src/main/java/org/kframework/kil/ASTNode.java
  kernel/src/main/java/org/kframework/kil/Module.java
  kernel/src/main/java/org/kframework/kil/Production.java
  kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java
  kernel/src/main/java/org/kframework/kore/convertors/KILtoKORE.java
  kernel/src/main/java/org/kframework/parser/ParserUtils.java
  kernel/src/main/java/org/kframework/utils/options/OuterParsingOptions.java
  kernel/src/main/javacc/Outer.jj
  kernel/src/test/java/org/kframework/kore/compile/GenerateSentencesFromConfigDeclTest.java
  kernel/src/test/java/org/kframework/parser/inner/RuleGrammarTest.java
  kernel/src/test/java/org/kframework/parser/inner/disambiguation/AddEmptyListsTest.java
  kernel/src/test/java/org/kframework/parser/json/JsonSerializationTests.java
  kernel/src/test/java/org/kframework/unparser/AddBracketsTest.java
  kore/src/main/scala/org/kframework/attributes/Att.scala
Labels: automerge, attributes

#3509 Update dependency: deps/hs-backend-booster_release
  deps/hs-backend-booster_release
  flake.lock
  flake.nix
Labels: automerge

#3512 Fix release build
  .github/actions/with-docker/action.yml
  .github/workflows/Dockerfile
  .github/workflows/release.yml
  README.md
  package/arch/Dockerfile.maven-cache
  package/debian/control.focal
Labels: automerge

#3513 Fix release JDK version
  .github/actions/test-package/action.yml
Labels: automerge

#3516 Set Arch release timeout to be longer
  .github/workflows/release.yml
Labels: automerge

#3523 Compare Attributes on Transformers
  kore/src/main/scala/org/kframework/definition/outer.scala
  kore/src/main/scala/org/kframework/definition/transformers.scala
Labels: enhancement, automerge, frontend, java

#3529 [ModuleToKore Refactoring] Creatign `GenerateMapCeilAxioms` compiler pass
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellRewriter.java
  kernel/src/main/java/org/kframework/backend/kore/KoreBackend.java
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  kernel/src/main/java/org/kframework/compile/GenerateMapCeilAxioms.java
  kore/src/main/scala/org/kframework/definition/outer.scala
Labels: module-to-kore, refactor, java

#3525 move integer lemmas out of code excluded by maude
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/tests/regression-new/domains-lemmas-no-smt/domains-lemmas-no-smt.k
  k-distribution/tests/regression-new/domains-lemmas-smt/domains-lemmas-smt.k
Labels: automerge

#3469 Remove unit applications in modules
  k-distribution/tests/regression-new/checks/removeUnit.k
  k-distribution/tests/regression-new/checks/removeUnit.k.out
  kernel/src/main/java/org/kframework/backend/kore/KoreBackend.java
  kernel/src/main/java/org/kframework/compile/RemoveUnit.java
Labels: automerge

#3543 update jung dependency
  kernel/pom.xml
  kernel/src/main/java/org/kframework/kdep/KDepFrontEnd.java
  kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java
  nix/mavenix.lock
Labels: automerge
