Repository runtimeverification/k, pull requests merged in 2023-06, with the labels that each got.

#3452 Update all K tests to use `group(_)`
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_1/imp.k
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_2/imp.k
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_3/imp.k
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_4/imp.k
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_5/imp.k
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_6/imp.k
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_7/imp.k
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_8/imp.md
  k-distribution/pl-tutorial/2_languages/1_simple/1_untyped/simple-untyped.md
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/2_dynamic/simple-typed-dynamic.md
  k-distribution/pl-tutorial/2_languages/2_kool/1_untyped/kool-untyped.md
  k-distribution/pl-tutorial/2_languages/2_kool/2_typed/1_dynamic/kool-typed-dynamic.md
  k-distribution/pl-tutorial/2_languages/2_kool/2_typed/2_static/kool-typed-static.md
  k-distribution/pl-tutorial/2_languages/3_fun/1_untyped/1_environment/fun-untyped.md
  k-distribution/tests/regression-new/imp++-llvm/imp.md
  k-distribution/tests/regression-new/issue-1372/test.k
  k-distribution/tests/regression-new/issue-1760/test.k
  k-distribution/tests/regression-new/issue-1760/test.k.out
  k-distribution/tests/regression-new/issue-999/kat.k
  k-distribution/tests/regression-new/issue-999/kat.k.out
  k-distribution/tests/regression-new/parse-c/c18-syntax.k
Labels: automerge, attributes

#3458 Fix EOF parsing error message crash
  k-distribution/include/kframework/ktest-fail.mak
  k-distribution/tests/regression-new/issue-3446/Makefile
  k-distribution/tests/regression-new/issue-3446/a.kast
  k-distribution/tests/regression-new/issue-3446/a.kast.out
  k-distribution/tests/regression-new/issue-3446/test.k
  k-distribution/tests/regression-new/issue-3446/test.k.out
  kore/src/main/java/org/kframework/utils/errorsystem/KException.java
Labels: automerge

#3455 Make the attribute whitelist opt-out
  k-distribution/k-tutorial/1_basic/04_disambiguation/README.md
  k-distribution/k-tutorial/1_basic/11_casts/README.md
  k-distribution/tests/regression-new/group/Makefile
  k-distribution/tests/regression-new/issue-1169/Makefile
  k-distribution/tests/regression-new/pedanticAttributes/Makefile
  kernel/src/main/java/org/kframework/utils/options/OuterParsingOptions.java
Labels: automerge, attributes

#3468 Update booster binary name to `kore-rpc-booster`
  flake.lock
  flake.nix
Labels: automerge

#3459 Add `generatedCounter` implicitly to claims
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_7/tests/proofs/sum-spec.k
  k-distribution/pl-tutorial/1_k/4_imp++/lesson_8/tests/proofs/sum-spec.k
  k-distribution/tests/regression-new/issue-3450-kprove-fresh/Makefile
  k-distribution/tests/regression-new/issue-3450-kprove-fresh/explicit-spec.k
  k-distribution/tests/regression-new/issue-3450-kprove-fresh/explicit-spec.k.out
  k-distribution/tests/regression-new/issue-3450-kprove-fresh/implicit-spec.k
  k-distribution/tests/regression-new/issue-3450-kprove-fresh/implicit-spec.k.out
  k-distribution/tests/regression-new/issue-3450-kprove-fresh/test.k
  kernel/src/main/java/org/kframework/backend/kore/KoreBackend.java
  kernel/src/main/java/org/kframework/compile/AddImplicitComputationCell.java
  kernel/src/main/java/org/kframework/compile/AddImplicitCounterCell.java
  kernel/src/main/java/org/kframework/compile/IncompleteCellUtils.java
Labels: automerge

#3476 Bumping install-nix-action to v22 and setting mac runners to macOS 13
  .github/workflows/master-push.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
  .github/workflows/update-deps.yml
Labels: automerge

#3454 Improve `--version` implementation on K script
  .gitignore
  k-distribution/src/main/scripts/lib/k
  kernel/pom.xml
Labels: enhancement, automerge

#3467 Update CheckKLabels to consider --concrete-rules
  k-distribution/tests/regression-new/concrete-function-cache/a1-spec.k
  k-distribution/tests/regression-new/concrete-function-cache/a2-spec.k
  k-distribution/tests/regression-new/concrete-function-cache/a2-spec.k.out
  k-distribution/tests/regression-new/concrete-function/a.k
  k-distribution/tests/regression-new/concrete-function/a1-spec.k
  k-distribution/tests/regression-new/concrete-function/a1-spec.k.out
  k-distribution/tests/regression-new/concrete-function/a2-spec.k
  k-distribution/tests/regression-new/issue-3385/Makefile
  k-distribution/tests/regression-new/issue-3385/test.k
  k-distribution/tests/regression-new/issue-3385/test.k.out
  kernel/src/main/java/org/kframework/compile/checks/CheckKLabels.java
  kernel/src/main/java/org/kframework/kompile/Kompile.java
Labels: automerge

#3482 Commit flake.lock
  flake.lock
Labels: automerge
