Repository runtimeverification/k, pull requests merged in 2023-02, with the labels that each got.

#3135 Find occurances
  kernel/src/main/java/org/kframework/lsp/KLanguageServer.java
  kernel/src/main/java/org/kframework/lsp/KPos.java
  kernel/src/main/java/org/kframework/lsp/KTextDocumentService.java
  kernel/src/main/java/org/kframework/lsp/TextDocumentSyncHandler.java
Labels: automerge

#3136 Depend on libboost-dev for bindings build
  package/debian/Dockerfile
  package/debian/control.bullseye
  package/debian/control.focal
  package/debian/control.jammy
Labels: automerge

#3149 Add proper error message
  kernel/src/main/java/org/kframework/compile/AddSortInjections.java
Labels: automerge

#3153 Fix github set-output files
  .github/workflows/release.yml
Labels: automerge

#3157 Make gh-pages an orphan branch
  .github/workflows/release.yml
Labels: automerge

#3158 ci: Removed web-related in Dockerfile
  Dockerfile
Labels: automerge

#3160 Fix some of the issues from Clarity on tutorial lessons
  k-distribution/k-tutorial/1_basic/04_disambiguation/README.md
  k-distribution/k-tutorial/1_basic/05_modules/README.md
  k-distribution/k-tutorial/1_basic/06_ints_and_bools/README.md
  k-distribution/k-tutorial/1_basic/07_side_conditions/README.md
  k-distribution/k-tutorial/1_basic/08_literate_programming/README.md
  k-distribution/k-tutorial/1_basic/09_unparsing/README.md
  k-distribution/k-tutorial/1_basic/11_casts/README.md
  k-distribution/k-tutorial/1_basic/13_rewrite_rules/README.md
  k-distribution/k-tutorial/1_basic/14_evaluation_order/README.md
  k-distribution/k-tutorial/1_basic/15_configurations/README.md
  k-distribution/k-tutorial/1_basic/16_collections/README.md
  k-distribution/k-tutorial/1_basic/17_cell_multiplicity/README.md
  k-distribution/k-tutorial/1_basic/18_equality_and_conditionals/README.md
  k-distribution/k-tutorial/1_basic/19_debugging/README.md
  k-distribution/k-tutorial/1_basic/20_backends/README.md
  k-distribution/k-tutorial/1_basic/21_symbolic_execution/README.md
Labels: automerge, documentation, tutorial, web

#3142 Klsp inner
  kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java
  kernel/src/main/java/org/kframework/kompile/Kompile.java
  kernel/src/main/java/org/kframework/kompile/KompileOptions.java
  kernel/src/main/java/org/kframework/lsp/KLanguageServer.java
  kernel/src/main/java/org/kframework/lsp/KPos.java
  kernel/src/main/java/org/kframework/lsp/KTextDocumentService.java
  kernel/src/main/java/org/kframework/lsp/KWorkspaceService.java
  kernel/src/main/java/org/kframework/lsp/TextDocumentSyncHandler.java
  kernel/src/main/java/org/kframework/parser/inner/ParseCache.java
  kernel/src/test/java/org/kframework/lsp/LSPTests.java
  kore/src/main/scala/org/kframework/definition/transformers.scala
  kore/src/main/scala/org/kframework/parser/TreeNodesToKORE.scala
Labels: automerge

#3171 Run llvm-kompile using relative paths
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMBackend.java
Labels: automerge

#3174 Fix another batch of suggestions from Clarity on tutorial lessons
  k-distribution/k-tutorial/1_basic/02_basics/README.md
  k-distribution/k-tutorial/1_basic/04_disambiguation/README.md
  k-distribution/k-tutorial/1_basic/07_side_conditions/README.md
  k-distribution/k-tutorial/1_basic/12_syntactic_lists/README.md
Labels: documentation, tutorial, web

#3173 Add selection range in lsp
  kernel/src/main/java/org/kframework/lsp/KLanguageServer.java
  kernel/src/main/java/org/kframework/lsp/KTextDocument.java
  kernel/src/main/java/org/kframework/lsp/KTextDocumentService.java
  kernel/src/main/java/org/kframework/lsp/TextDocumentSyncHandler.java
Labels: automerge

#3182 Fix path to k-exercises repo
  .github/workflows/test-pr.yml
Labels: automerge

#3176 [K MD Parser] Extend TagSelector to Support Line Numbers in Code Blocks
  k-distribution/tests/regression-new/markdownSelectors/Makefile
  k-distribution/tests/regression-new/markdownSelectors/a-spec.md.out
  k-distribution/tests/regression-new/markdownSelectors/test.md
  kernel/src/main/jjtree/TagSelector.jjt
  kernel/src/test/java/org/kframework/parser/outer/MDsourceTest.java
Labels: automerge, feature, frontend

#3184 Add line numbers to the debugging tutorial
  k-distribution/k-tutorial/1_basic/19_debugging/README.md
Labels: automerge, tutorial, web

#3181 Update simple to llvm backend
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/1_static/Makefile
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/1_static/simple-typed-static.md
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/2_dynamic/Makefile
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/2_dynamic/exercises/functions-with-throws/tests/div-nondet.simple.out
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/2_dynamic/exercises/functions-with-throws/tests/threads_05.simple.out
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/2_dynamic/exercises/typed-exceptions/tests/div-nondet.simple.out
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/2_dynamic/exercises/typed-exceptions/tests/threads_05.simple.out
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/2_dynamic/simple-typed-dynamic.md
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/2_dynamic/tests/div-nondet.simple.out
  k-distribution/pl-tutorial/2_languages/1_simple/2_typed/2_dynamic/tests/threads_05.simple.out
Labels: automerge

#3183 Fix issue with special characters in path
  k-distribution/src/main/scripts/lib/setenv
Labels: automerge

#3186 Exclude nix result dir from checkstyle
  pom.xml
Labels: automerge

#3190 .github/: update nix/cachix actions
  .github/workflows/master-push.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
  .github/workflows/update-deps.yml
Labels: automerge

#3198 Fix loc info for gen config cells
  k-distribution/tests/regression-new/cell-bag-sort-llvm/test.k.out
  kernel/src/main/java/org/kframework/compile/GenerateSentencesFromConfigDecl.java
Labels: automerge
