Repository runtimeverification/k, pull requests merged in 2024-08, with the labels that each got.

#4566 Display number of terminal nodes in `one_line_summary` for `APRProof`
  pyk/src/pyk/proof/reachability.py
Labels: automerge

#4573 Remove the deprecated `"log-timing"` RPC log option
  pyk/src/pyk/kore/rpc.py
  pyk/src/tests/integration/kore/test_kore_client.py
Labels: automerge

#4563 Support for non-immediate proof maintenance
  pyk/src/pyk/proof/proof.py
Labels: enhancement

#4575 Status bar improvements
  pyk/src/pyk/proof/reachability.py
Labels: automerge

#4577 Removing minimize_constraints and adding ability to use booster implies
  pyk/src/pyk/cli/pyk.py
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/pyk/kcfg/explore.py
  pyk/src/pyk/kore/rpc.py
  pyk/src/pyk/ktool/prove_rpc.py
  pyk/src/pyk/proof/implies.py
  pyk/src/pyk/proof/reachability.py
  pyk/src/tests/integration/cterm/test_simple.py
  pyk/src/tests/unit/kore/test_client.py
Labels: enhancement

#4562 fix bug in mint inference
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/tests/regression-new/mint-llvm-3/Makefile
  k-distribution/tests/regression-new/mint-llvm-3/test.k
  k-frontend/src/main/java/org/kframework/compile/AddSortInjections.java
  k-frontend/src/main/java/org/kframework/parser/inner/RuleGrammarGenerator.java
  k-frontend/src/main/java/org/kframework/parser/inner/disambiguation/TypeInferenceVisitor.java
Labels: automerge

#4581 Bug not allowing `--smt-retry-limit 0`
  pyk/src/pyk/kore/rpc.py
Labels: automerge

#4580 Redesigning rewrite logging
  pyk/src/pyk/cterm/symbolic.py
Labels: enhancement

#4532 Adding `--proof-hint` flag to PyK KRun
  pyk/src/pyk/ktool/krun.py
  pyk/src/tests/integration/test_krun_proof_hints.py
  pyk/src/tests/unit/ktool/test_krun.py
Labels: automerge, feature, pyk

#4586 Update dependency: deps/z3
  deps/z3
Labels: automerge

#4589 Fixing indentation in `run_proof_hint`
  pyk/src/pyk/ktool/krun.py
Labels: bug, automerge

#4585 APRProof get_steps optimizations
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/pyk/proof/reachability.py
Labels: automerge

#4588 Add parser tests for `pyk.kore.syntax.String`
  pyk/src/tests/unit/kore/test_parser.py
Labels: automerge, pyk

#4583 --no-clean option for kdist build
  pyk/src/pyk/kdist/__main__.py
  pyk/src/pyk/kdist/_kdist.py
Labels: automerge

#4590 Reusing backend information to construct KCFGs more efficiently
  pyk/src/pyk/kcfg/explore.py
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/pyk/kcfg/semantics.py
  pyk/src/pyk/proof/reachability.py
  pyk/src/tests/integration/ktool/test_imp.py
  pyk/src/tests/integration/proof/test_custom_step.py
  pyk/src/tests/integration/proof/test_goto.py
  pyk/src/tests/integration/proof/test_imp.py
  pyk/src/tests/integration/proof/test_refute_node.py
  pyk/src/tests/integration/proof/test_simple.py
Labels: enhancement

#4597 Add syntactic to whitelist
  k-frontend/src/main/java/org/kframework/compile/checks/CheckAtt.java
  k-frontend/src/main/scala/org/kframework/attributes/Att.scala
Labels: automerge

#4596 Don't trim list separators
  k-frontend/src/main/java/org/kframework/kil/UserList.java
Labels: automerge

#4593 Custom printing for KFuzz
  pyk/src/pyk/ktool/kfuzz.py
  pyk/src/pyk/ktool/krun.py
Labels: automerge

#4601 Start `kdist` workers with `spawn`
  pyk/src/pyk/kdist/__main__.py
  pyk/src/pyk/kdist/_kdist.py
  pyk/src/pyk/kdist/utils.py
Labels: automerge, pyk

#4607 Move kcfg.minimize into a separate file and class
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/pyk/kcfg/minimize.py
  pyk/src/tests/unit/kcfg/test_minimize.py
  pyk/src/tests/unit/test_kcfg.py
  pyk/src/tests/unit/test_proof.py
Labels: automerge

#4603 MergedEdge class for merging node functionality
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/pyk/kcfg/show.py
  pyk/src/pyk/kcfg/tui.py
  pyk/src/pyk/proof/reachability.py
  pyk/src/tests/unit/test_kcfg.py
Labels: automerge

#4610 Basic defunctionalization for building rules in K
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cterm/cterm.py
  pyk/src/pyk/kast/manip.py
  pyk/src/pyk/kast/outer.py
  pyk/src/pyk/kcfg/exploration.py
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/pyk/kcfg/minimize.py
  pyk/src/pyk/kcfg/show.py
  pyk/src/tests/integration/cterm/test_simple.py
  pyk/src/tests/integration/proof/test_refute_node.py
  pyk/src/tests/unit/kast/test_manip.py
Labels: automerge

#4611 Cleanup CI steps
  .github/workflows/develop.yml
  .github/workflows/release.yml
Labels: automerge

#4529 Move bug report handling from `Transport` to `JsonRpcClient`
  pyk/src/pyk/kore/rpc.py
  pyk/src/tests/unit/kore/test_rpc_client.py
Labels: automerge
