Repository runtimeverification/k, pull requests merged in 2024-09, with the labels that each got.

#4615 Set pyk version with `importlib.metadata.version`
  package/version.sh
  pyk/src/pyk/__init__.py
Labels: automerge

#4622 Fix MacOS brew release
  .github/workflows/release.yml
Labels: automerge

#4623 release.yml: On failure run publish with verbose option enabled
  .github/workflows/release.yml
Labels: automerge

#4631 Improvements/refactors to substitution extraction routine
  pyk/src/pyk/kast/manip.py
  pyk/src/tests/unit/kast/test_subst.py
Labels: automerge

#4632 Add tests for T-division using `llvm_interpret`
  pyk/src/tests/integration/test_division_hooks.py
Labels: automerge, pyk

#4630 Refactoring to KCFG printer for CSubst
  pyk/regression-new/kprove-haskell/sum-spec.k.out
  pyk/regression-new/kprove-haskell/test-spec.k.out
  pyk/src/pyk/__main__.py
  pyk/src/pyk/kast/manip.py
  pyk/src/pyk/kcfg/show.py
  pyk/src/tests/unit/kcfg/test_minimize.py
  pyk/src/tests/unit/test_kcfg.py
Labels: automerge

#4633 Adjust the sort of `mlEquals`
  pyk/src/pyk/prelude/ml.py
  pyk/src/tests/integration/proof/test_imp.py
  pyk/src/tests/unit/kast/test_subst.py
  pyk/src/tests/unit/test_kcfg.py
Labels: automerge

#4625 Cleanups to handling ml predicates and substitutions
  pyk/src/pyk/cterm/cterm.py
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/pyk/kast/inner.py
  pyk/src/pyk/kcfg/show.py
  pyk/src/pyk/kcfg/tui.py
  pyk/src/pyk/proof/reachability.py
  pyk/src/tests/unit/kast/test_subst.py
  pyk/src/tests/unit/test_cterm.py
Labels: automerge

#4635 Minimize substitutions by default
  pyk/src/pyk/kcfg/show.py
  pyk/src/tests/unit/test_kcfg.py
Labels: automerge

#4636 More readable and informative status bar
  pyk/src/pyk/proof/reachability.py
Labels: enhancement

#4637 Impure attribute in KORE
  k-frontend/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  k-frontend/src/main/java/org/kframework/compile/ComputeTransitiveFunctionDependencies.java
  k-frontend/src/main/scala/org/kframework/attributes/Att.scala
Labels: automerge

#4634 Handle list random access patterns in frontend
  docs/user_manual.md
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/tests/regression-new/list-set/00.test
  k-distribution/tests/regression-new/list-set/00.test.out
  k-distribution/tests/regression-new/list-set/01.test
  k-distribution/tests/regression-new/list-set/01.test.out
  k-distribution/tests/regression-new/list-set/11.test
  k-distribution/tests/regression-new/list-set/11.test.out
  k-distribution/tests/regression-new/list-set/22.test
  k-distribution/tests/regression-new/list-set/22.test.out
  k-distribution/tests/regression-new/list-set/Makefile
  k-distribution/tests/regression-new/list-set/test.k
  k-frontend/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
  k-frontend/src/main/java/org/kframework/compile/checks/CheckFunctions.java
  k-frontend/src/main/java/org/kframework/utils/errorsystem/KEMException.java
  k-frontend/src/main/scala/org/kframework/attributes/Att.scala
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMBackend.java
  pyk/src/pyk/kast/att.py
  pyk/src/pyk/konvert/_module_to_kore.py
Labels: automerge

#4641 Correct how pyk loads seqstrict attribute
  pyk/regression-new/seqstrict-predicate/1.test.out
  pyk/regression-new/skipped
  pyk/src/pyk/kast/att.py
Labels: automerge

#4644 No trimming of split constraints when printed
  pyk/src/pyk/kcfg/show.py
Labels: enhancement, automerge

#4643 Introducing the `LLVMPatternMatchingFailureEvent` class in ProofTrace module
  pyk/src/pyk/kllvm/hints/prooftrace.py
  pyk/src/tests/integration/kllvm/test_prooftrace.py
Labels: automerge

#4650 Adding is-loop functionality
  pyk/src/pyk/kcfg/semantics.py
  pyk/src/pyk/proof/reachability.py
  pyk/src/tests/integration/ktool/test_imp.py
  pyk/src/tests/integration/proof/test_custom_step.py
  pyk/src/tests/integration/proof/test_goto.py
  pyk/src/tests/integration/proof/test_imp.py
  pyk/src/tests/integration/proof/test_refute_node.py
  pyk/src/tests/integration/proof/test_simple.py
Labels: automerge
