Repository runtimeverification/k, pull requests merged in 2024-10, with the labels that each got.

#4654 Bug: Correctly typing and initialising `prior_loops_cache`
  pyk/src/pyk/proof/reachability.py
Labels: bug

#4647 Avoid using `merge_nodes` by default
  pyk/src/pyk/kcfg/exploration.py
  pyk/src/pyk/kcfg/minimize.py
  pyk/src/tests/unit/kcfg/merge_node_data.py
Labels: automerge

#4499 Fix `match_with_constraint`
  pyk/src/pyk/cterm/cterm.py
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/pyk/kcfg/minimize.py
  pyk/src/tests/integration/proof/test_refute_node.py
  pyk/src/tests/unit/kcfg/test_minimize.py
  pyk/src/tests/unit/test_cterm.py
  pyk/src/tests/unit/test_kcfg.py
Labels: automerge

#4656 Add Python 3.13 to `pyk` code quality CI job
  .github/workflows/test-pr.yml
  pyk/src/tests/integration/proof/test_imp.py
  pyk/src/tests/integration/proof/test_mini_kevm.py
Labels: automerge, pyk

#4657 TOML: use `default` profile values by default when another profile is active
  pyk/src/pyk/cli/pyk.py
  pyk/src/tests/unit/test-data/pyk_toml_test.toml
  pyk/src/tests/unit/test_toml_args.py
Labels: automerge

#4662 Marking simplifications that preserve definedness
  k-distribution/include/kframework/builtin/domains.md
Labels: enhancement, automerge

#4666 add hidden visibility flag
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMBackend.java
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMKompileOptions.java
Labels: automerge

#4673 Adding Timer Hook Implementation for K
  k-distribution/include/kframework/builtin/timer.md
  k-frontend/src/main/java/org/kframework/builtin/Hooks.java
  pyk/regression-new/imp-timer/Makefile
  pyk/regression-new/imp-timer/collatz.imp
  pyk/regression-new/imp-timer/collatz.imp.out
  pyk/regression-new/imp-timer/imp.k
  pyk/regression-new/imp-timer/primes.imp
  pyk/regression-new/imp-timer/primes.imp.out
  pyk/regression-new/imp-timer/sum.imp
  pyk/regression-new/imp-timer/sum.imp.out
Labels: automerge
