Repository runtimeverification/k, pull requests merged in 2024-04, with the labels that each got.

#4145 Refactor `addKoreAttributes`
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
Labels: automerge, attributes

#4158 Only allow letters as first character in `MODNAME`
  kernel/src/main/javacc/Outer.jj
Labels: automerge

#4146 Only generate syntactic attributes for `syntaxDefinition.kore`
  k-distribution/tests/regression-new/map-symbolic-tests-haskell/assignment-11-spec.k.out
  kernel/src/main/java/org/kframework/backend/kore/ModuleToKORE.java
Labels: automerge

#4160 Add test for `no-evaluators` exhaustiveness
  k-distribution/tests/regression-new/checkWarns/noEvaluatorsExhaustive.k
  k-distribution/tests/regression-new/checkWarns/noEvaluatorsExhaustive.k.out
Labels: automerge

#4162 Improve error handling for missing syntax/main module
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellBackend.java
  k-distribution/src/test/scala/org/kframework/backend/kore/KoreTest.scala
  k-distribution/tests/regression-new/issue-4153-missing-module/Makefile
  k-distribution/tests/regression-new/issue-4153-missing-module/test.k
  k-distribution/tests/regression-new/issue-4153-missing-module/test.k.out
  kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java
  kernel/src/main/java/org/kframework/kompile/Kompile.java
  kernel/src/main/java/org/kframework/kompile/KompileOptions.java
  kernel/src/main/java/org/kframework/kprove/ProofDefinitionBuilder.java
  kernel/src/main/java/org/kframework/parser/ParserUtils.java
  kernel/src/test/java/org/kframework/compile/GenerateSentencesFromConfigDeclTest.java
  kernel/src/test/java/org/kframework/kompile/KompileOptionsTest.java
  kernel/src/test/java/org/kframework/parser/inner/RuleGrammarTest.java
  kernel/src/test/java/org/kframework/parser/inner/disambiguation/AddEmptyListsTest.java
  kernel/src/test/java/org/kframework/unparser/AddBracketsTest.java
Labels: automerge

#4240 Bump nix tools repo
  flake.lock
Labels: automerge

#4243 Use `--warnings-to-errors` in tests
  pyk/regression-new/bad-bytes-literal/quote.k.out
  pyk/regression-new/bad-bytes-literal/slash.k.out
  pyk/regression-new/bad-bytes-literal/unicode-escape.k.out
  pyk/regression-new/bad-bytes-literal/unicode.k.out
  pyk/regression-new/cell-bag-sort-llvm/test.k.out
  pyk/regression-new/checkWarns/checkHaskellAnywhere.k.out
  pyk/regression-new/checkWarns/checkRHSHaskell.k.out
  pyk/regression-new/checkWarns/checkUnusedSymbol.k.out
  pyk/regression-new/checkWarns/checkUnusedVar.k.out
  pyk/regression-new/checkWarns/deprecated.k.out
  pyk/regression-new/checkWarns/existsLHSBoundFail.k.out
  pyk/regression-new/checkWarns/missingKlabel.k.out
  pyk/regression-new/checkWarns/nullarySymbol.k.out
  pyk/regression-new/checkWarns/requireBuiltinK.k.out
  pyk/regression-new/checkWarns/singletonOverload.k.out
  pyk/regression-new/checkWarns/syntaxGroups.k.out
  pyk/regression-new/excludedModuleAtts/haskell/test-entry.k.out
  pyk/regression-new/excludedModuleAtts/haskell/test-main.k.out
  pyk/regression-new/excludedModuleAtts/llvm/test-entry.k.out
  pyk/regression-new/excludedModuleAtts/llvm/test-main.k.out
  pyk/regression-new/fatalWarnings/test.k.out
  pyk/regression-new/issue-1545-func-in-simplification/test.k.out
  pyk/regression-new/issue-1572/test.k.out
  pyk/regression-new/issue-2146-duplicateModules/test.k.out
  pyk/regression-new/issue-313/test.k.out
  pyk/regression-new/issue-3385/test.k.out
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cli/args.py
  pyk/src/pyk/ktool/kompile.py
  pyk/src/pyk/testing/_kompiler.py
  pyk/src/tests/integration/cterm/test_simple.py
  pyk/src/tests/integration/konvert/test_simple_proofs.py
  pyk/src/tests/integration/kprove/test_prove_claim_with_lemmas.py
  pyk/src/tests/integration/proof/test_simple.py
  pyk/src/tests/integration/test_json_rpc.py
Labels: automerge, pyk

#4246 Add separate get proof steps and execute proof step phase
  pyk/src/pyk/proof/implies.py
  pyk/src/pyk/proof/proof.py
  pyk/src/pyk/proof/reachability.py
Labels: automerge

#4172 add spec module in definition_args
  pyk/src/pyk/cli/args.py
Labels: automerge, pyk

#4245 Add proof exploration and display options to CLI
  pyk/regression-new/kprove-haskell/Makefile
  pyk/regression-new/kprove-haskell/sum-spec.k.out
  pyk/regression-new/kprove-haskell/test-fail-spec.k.out
  pyk/regression-new/kprove-haskell/test-spec.k.out
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cli/args.py
  pyk/src/pyk/cli/pyk.py
  pyk/src/pyk/ktool/kprint.py
  pyk/src/pyk/ktool/kprove.py
  pyk/src/tests/integration/ktool/test_imp.py
Labels: automerge, pyk

#4258 Fix overflow bug when sorting tokens by precedence
  k-distribution/tests/regression-new/regex-prec/1.test.kast
  k-distribution/tests/regression-new/regex-prec/1.test.kast.out
  k-distribution/tests/regression-new/regex-prec/Makefile
  k-distribution/tests/regression-new/regex-prec/test.k
  kernel/src/main/java/org/kframework/parser/inner/kernel/Scanner.java
Labels: automerge

#4261 Sort ambiguities generated by GLR Bison parsers
  k-distribution/include/kframework/cparser/main.c
  k-distribution/tests/regression-new/parse-c/test.ref
Labels: automerge

#4262 cli/args: remove now redundant spec_module
  pyk/src/pyk/cli/args.py
Labels: automerge

#4241 Allow a custom `--kore-rpc-command` in `pyk prove`
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cli/pyk.py
  pyk/src/pyk/kore/rpc.py
  pyk/src/pyk/ktool/kprove.py
Labels: automerge

#4252 Pyk: Attribute token locations
  pyk/src/pyk/kast/outer_lexer.py
  pyk/src/tests/unit/kast/test_outer_lexer.py
  pyk/src/tests/unit/test-data/outer-lexer/attr-key-with-dots.test
  pyk/src/tests/unit/test-data/outer-lexer/bubble-multi-line.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-01-array.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-02-map.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-03-rangemap.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-04-collections.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-05-bool.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-06-int.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-07-float.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-08-string.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-09-bytes.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-10-id.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-11-k.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-12-io.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-13-mint.test
  pyk/src/tests/unit/test-data/outer-lexer/domains-14-strategy.test
  pyk/src/tests/unit/test-data/outer-lexer/imp-syntax.test
  pyk/src/tests/unit/test-data/outer-lexer/rule-label-attr.test
  pyk/src/tests/unit/test-data/outer-lexer/rule-stdin-getc.test
  pyk/src/tests/unit/test-data/outer-lexer/syntax-group-attr.test
  pyk/src/tests/unit/test-data/outer-lexer/syntax-set.test
Labels: automerge

#4249 Ordered constraint accumulation
  pyk/regression-new/kprove-haskell/sum-spec.k.out
  pyk/src/pyk/cterm/cterm.py
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/tests/integration/proof/test_imp.py
  pyk/src/tests/unit/test_kcfg.py
Labels: enhancement, automerge, pyk

#4248 Refactoring the branching mechanism
  pyk/regression-new/kprove-haskell/sum-spec.k.out
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/pyk/kcfg/explore.py
  pyk/src/pyk/kcfg/semantics.py
  pyk/src/tests/integration/cterm/test_multiple_definitions.py
  pyk/src/tests/integration/cterm/test_simple.py
  pyk/src/tests/integration/ktool/test_imp.py
  pyk/src/tests/integration/proof/test_goto.py
  pyk/src/tests/integration/proof/test_imp.py
  pyk/src/tests/integration/proof/test_refute_node.py
  pyk/src/tests/integration/proof/test_simple.py
Labels: enhancement, automerge, pyk

#4254 add toml support for pyk options
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cli/args.py
  pyk/src/pyk/cli/cli.py
  pyk/src/pyk/cli/pyk.py
  pyk/src/tests/unit/test-data/pyk_toml_test.toml
  pyk/src/tests/unit/test_toml_args.py
Labels: automerge, pyk

#4280 Terminal node subsumption check correction
  pyk/src/pyk/proof/reachability.py
  pyk/src/tests/integration/proof/test_imp.py
  pyk/src/tests/integration/test-data/k-files/imp-simple-spec.k
Labels: bug, automerge

#4281 Revert constraint unsortedness
  pyk/regression-new/kprove-haskell/sum-spec.k.out
  pyk/src/pyk/cterm/cterm.py
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/pyk/kast/inner.py
  pyk/src/pyk/kast/manip.py
  pyk/src/pyk/prelude/ml.py
  pyk/src/tests/integration/kprove/test_emit_json_spec.py
  pyk/src/tests/integration/kprove/test_print_prove_rewrite.py
  pyk/src/tests/integration/kprove/test_prove_claim_with_lemmas.py
  pyk/src/tests/integration/proof/test_imp.py
Labels: automerge

#4286 Move long-running pyk tests into Docker container
  .github/actions/setup-pyk-env/action.yml
  .github/actions/with-k-docker/Dockerfile
  .github/actions/with-k-docker/action.yml
  .github/workflows/test-pr.yml
  pyk/src/pyk/rpc/rpc.py
  pyk/src/tests/integration/test_json_rpc.py
Labels: automerge

#4294 Improving rule creation
  pyk/regression-new/kprove-haskell/sum-spec.k.out
  pyk/src/pyk/kast/manip.py
  pyk/src/tests/integration/konvert/test_simple_proofs.py
  pyk/src/tests/unit/kast/test_manip.py
Labels: enhancement, automerge

#4270 Add `parse-outer` command to pyk
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cli/pyk.py
  pyk/src/pyk/kast/__init__.py
  pyk/src/pyk/kast/_ast_to_kast.py
  pyk/src/pyk/kast/markdown.py
  pyk/src/pyk/kast/utils.py
  pyk/src/tests/unit/kast/test_ast_to_kast.py
  pyk/src/tests/unit/kast/test_utils.py
  pyk/src/tests/unit/test-data/parse-outer/a.k
  pyk/src/tests/unit/test-data/parse-outer/a.k.expected.json
  pyk/src/tests/unit/test-data/parse-outer/a.k.out.json
  pyk/src/tests/unit/test-data/parse-outer/b.k
  pyk/src/tests/unit/test-data/parse-outer/b.k.expected.json
  pyk/src/tests/unit/test-data/parse-outer/b.k.out.json
  pyk/src/tests/unit/test-data/parse-outer/c.k
  pyk/src/tests/unit/test-data/parse-outer/c.k.expected.json
  pyk/src/tests/unit/test-data/parse-outer/d.k
  pyk/src/tests/unit/test-data/parse-outer/d.k.expected.json
  pyk/src/tests/unit/test-data/parse-outer/include.k
  pyk/src/tests/unit/test-data/parse-outer/include.k.expected.json
  pyk/src/tests/unit/test-data/parse-outer/include/e.k
  pyk/src/tests/unit/test-data/parse-outer/markdown.md
  pyk/src/tests/unit/test-data/parse-outer/markdown.md.expected.json
Labels: automerge
