Repository runtimeverification/k, pull requests merged in 2024-06, with the labels that each got.

#4404 remove default values from argparse
  pyk/src/pyk/cli/args.py
Labels: bug, automerge

#4388 Pretty print brackets in `Formatter`
  pyk/src/pyk/kast/att.py
  pyk/src/pyk/kast/formatter.py
  pyk/src/pyk/kast/outer.py
  pyk/src/pyk/konvert/_module_to_kore.py
  pyk/src/tests/integration/kast/test_formatter.py
Labels: automerge, pyk

#4407 Adding inline documentation to `prooftrace.py`
  pyk/src/pyk/kllvm/hints/__init__.py
  pyk/src/pyk/kllvm/hints/prooftrace.py
Labels: automerge, documentation, pyk

#4410 Fix `KLabel` for `#Exists`
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/pyk/konvert/_kast_to_kore.py
  pyk/src/pyk/konvert/_kore_to_kast.py
  pyk/src/pyk/prelude/ml.py
  pyk/src/tests/integration/konvert/test_simple_proofs.py
Labels: automerge

#4411 Claim dependencies included as subproofs
  pyk/src/pyk/kcfg/explore.py
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/pyk/proof/reachability.py
  pyk/src/tests/integration/proof/test_custom_step.py
  pyk/src/tests/integration/proof/test_mini_kevm.py
Labels: automerge

#4417 Extract `KSequence` elimination as a pass in KAST-to-KORE
  pyk/src/pyk/konvert/_kast_to_kore.py
Labels: automerge, pyk

#4424 Symlink `booster-dev` binary into bin/ in the final k derivation
  nix/k.nix
Labels: automerge

#4421 Adding new proof trace tests from Pi2
  pyk/src/tests/integration/kllvm/test_prooftrace.py
Labels: automerge, testing

#4420 Add `pyk` documentation generation script
  .github/actions/with-k-docker/Dockerfile
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
  pyk/Makefile
  pyk/docs/generate.sh
  pyk/poetry.lock
  pyk/pyproject.toml
Labels: pyk

#4432 Escape literal spaces in Flex regex
  k-frontend/src/main/java/org/kframework/definition/regex/RegexSyntax.java
Labels: automerge

#4430 Drop remaining uses of Intel macOS in CI
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
Labels: automerge

#4436 Refactor `parse_outer`
  pyk/src/pyk/__main__.py
  pyk/src/pyk/kast/utils.py
  pyk/src/tests/unit/kast/test_utils.py
Labels: automerge, pyk

#4439 Align Pyk's nixpkgs version to the shared K version
  pyk/flake.lock
  pyk/flake.nix
Labels: automerge

#4427 Allow specifying that an APRProof generated lemmas should be direct
  pyk/src/pyk/proof/proof.py
  pyk/src/pyk/proof/reachability.py
Labels: automerge

#4440 Allow a longer time for Pyk documentation builds
  .github/workflows/release.yml
Labels: automerge

#4438 Rename the `pyk` distribution package to `kframework`
  pyk/.cruft.json
  pyk/README.md
  pyk/pyproject.toml
Labels: automerge

#4441 Bump minor version to 7.1.0
  CHANGELOG.md
  install-k
  package/debian/changelog
  package/version
  pyk/docs/conf.py
  pyk/pyproject.toml
  pyk/src/pyk/__init__.py
Labels: automerge

#4308 Reorganise CI to use pre-packaged LLVM backend release
  .github/actions/with-k-docker/Dockerfile
  .github/actions/with-k-docker/action.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
  k-distribution/tests/profiling/setup_profiling.sh
  package/debian/build-package
  package/debian/kframework-frontend/changelog
  package/debian/kframework-frontend/compat.jammy
  package/debian/kframework-frontend/control.jammy
  package/debian/kframework-frontend/copyright
  package/debian/kframework-frontend/kframework-frontend-docs.docs
  package/debian/kframework-frontend/rules.jammy
  package/debian/kframework-frontend/source/format
  package/debian/kframework/changelog
  package/debian/kframework/compat.jammy
  package/debian/kframework/control.jammy
  package/debian/kframework/copyright
  package/debian/kframework/kframework-docs.docs
  package/debian/kframework/rules.jammy
  package/debian/kframework/source/format
  package/debian/test-frontend-package
  package/package
  package/version.sh
Labels: automerge

#4443 Add labels to INT-to-ML rules in `domains.md`
  k-distribution/include/kframework/builtin/domains.md
Labels: automerge

#4444 Extract class `ClaimIndex`
  pyk/src/pyk/kast/outer.py
  pyk/src/pyk/ktool/kprove.py
Labels: automerge

#4448 Escape @ in _make_module_name
  pyk/src/pyk/proof/reachability.py
Labels: bug, automerge

#4445 Cut on circularity rule application, better error message
  pyk/src/pyk/kcfg/explore.py
  pyk/src/pyk/kore/rpc.py
  pyk/src/pyk/proof/reachability.py
  pyk/src/tests/integration/proof/test_imp.py
Labels: automerge

#4449 Remove module `pyk.proof.parallel`
  pyk/src/pyk/proof/parallel.py
  pyk/src/tests/integration/proof/test_parallel_prove.py
Labels: automerge, pyk

#4458 Revert "Align Pyk's nixpkgs version to the shared K version"
  pyk/flake.lock
  pyk/flake.nix
Labels: automerge

#4460 Update `pyk` dependencies
  pyk/docs/generate.sh
  pyk/poetry.lock
Labels: automerge, pyk

#4459 Use Java standard SHA3 implementation
  flake.nix
  k-frontend/pom.xml
  k-frontend/src/main/java/org/kframework/compile/NumberSentences.java
Labels: automerge

#4461 Extract release job `notify-dependents`
  .github/workflows/release.yml
Labels: automerge

#4463 Fix version update request
  .github/workflows/release.yml
Labels: automerge

#4464 Fix docs build release job
  .github/actions/with-k-docker/Dockerfile
  .github/actions/with-k-docker/action.yml
  .github/workflows/release.yml
Labels: automerge

#4416 Publish `pyk` on PyPI
  .github/workflows/release.yml
Labels: automerge

#4467 Revert "Revert "Align Pyk's nixpkgs version to the shared K version""
  pyk/flake.lock
  pyk/flake.nix
Labels: automerge

#4455 Support `#Or` in `kore_to_kast`
  pyk/src/pyk/konvert/_kore_to_kast.py
Labels: automerge

#4450 Rewrite docstrings in Google style
  pyk/Makefile
  pyk/poetry.lock
  pyk/pyproject.toml
  pyk/src/pyk/__main__.py
  pyk/src/pyk/coverage.py
  pyk/src/pyk/cterm/cterm.py
  pyk/src/pyk/kast/formatter.py
  pyk/src/pyk/kast/inner.py
  pyk/src/pyk/kast/lexer.py
  pyk/src/pyk/kast/manip.py
  pyk/src/pyk/kast/outer.py
  pyk/src/pyk/kast/outer_lexer.py
  pyk/src/pyk/kast/pretty.py
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/pyk/kcfg/show.py
  pyk/src/pyk/kllvm/hints/prooftrace.py
  pyk/src/pyk/konvert/_module_to_kore.py
  pyk/src/pyk/kore/rpc.py
  pyk/src/pyk/kore/syntax.py
  pyk/src/pyk/kore_exec_covr/__main__.py
  pyk/src/pyk/kore_exec_covr/kore_exec_covr.py
  pyk/src/pyk/krepl/repl.py
  pyk/src/pyk/ktool/kprove.py
  pyk/src/pyk/ktool/krun.py
  pyk/src/pyk/proof/proof.py
  pyk/src/pyk/proof/reachability.py
Labels: automerge, documentation, pyk

#4451 Change the `pyk` API docs theme
  pyk/docs/conf.py
  pyk/docs/generate.sh
Labels: automerge, documentation, pyk

#4454 Begin implementing fuzzing
  pyk/poetry.lock
  pyk/pyproject.toml
  pyk/src/pyk/ktool/kfuzz.py
  pyk/src/pyk/ktool/krun.py
  pyk/src/tests/integration/ktool/test_fuzz.py
Labels: automerge

#4447 Refactor `from_spec_modules` in `APRProof`
  pyk/src/pyk/__main__.py
  pyk/src/pyk/ktool/claim_index.py
  pyk/src/pyk/ktool/kprove.py
  pyk/src/pyk/ktool/prove_rpc.py
  pyk/src/pyk/proof/reachability.py
  pyk/src/tests/integration/ktool/test_imp.py
Labels: automerge

#4472 add two important missing flags to the llvm backend compiler
  pyk/src/pyk/ktool/kompile.py
Labels: automerge

#4471 Expose `-Wno` via `ignore-warnings` kompile option
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cli/args.py
  pyk/src/pyk/ktool/kompile.py
Labels: enhancement, automerge

#4486 Fix link in `toc.md`
  web/toc.md
Labels: automerge

#4483 add command line flag to enable debug info in proof trace
  k-distribution/tests/regression-new/proof-instrumentation-debug/.gitignore
  k-distribution/tests/regression-new/proof-instrumentation-debug/Makefile
  k-distribution/tests/regression-new/proof-instrumentation-debug/input.test
  k-distribution/tests/regression-new/proof-instrumentation-debug/input.test.out
  k-distribution/tests/regression-new/proof-instrumentation-debug/test.k
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMBackend.java
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMKompileOptions.java
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cli/args.py
  pyk/src/pyk/ktool/kompile.py
Labels: automerge

#4480 Fix bug report request IDs being reset when using multiple `KoreClient`s
  pyk/src/pyk/kore/rpc.py
  pyk/src/tests/unit/kore/test_rpc_client.py
Labels: automerge

#4482 Add RangeMap functionality to Pyk
  pyk/src/pyk/kast/manip.py
  pyk/src/pyk/kast/outer.py
  pyk/src/pyk/kore/match.py
  pyk/src/pyk/kore/prelude.py
  pyk/src/pyk/prelude/collections.py
  pyk/src/tests/unit/kore/test_match.py
Labels: automerge

#4490 Delay further steps / jobs until kframework is available on PyPi
  .github/workflows/release.yml
Labels: automerge
