Repository runtimeverification/k, pull requests merged in 2024-05, with the labels that each got.

#4275 Remove precede/follow regex from `RegexTerminal`
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/include/kframework/builtin/kast.md
  k-distribution/include/kframework/builtin/substitution.md
  k-distribution/tests/regression-new/bison-glr-bug/iele.k
  k-distribution/tests/regression-new/issue-3647-debugTokens/a.test.kast.out
  k-distribution/tests/regression-new/issue-3647-debugTokens/b.test.kast.out
  k-frontend/src/main/java/org/kframework/kore/convertors/KILtoKORE.java
  k-frontend/src/main/java/org/kframework/parser/json/JsonParser.java
  k-frontend/src/main/java/org/kframework/unparser/ToJson.java
  k-frontend/src/main/scala/org/kframework/definition/Constructors.scala
  k-frontend/src/main/scala/org/kframework/definition/outer-to-string.scala
  k-frontend/src/main/scala/org/kframework/definition/outer.scala
  k-frontend/src/test/java/org/kframework/parser/inner/RuleGrammarTest.java
  k-frontend/src/test/java/org/kframework/unparser/AddBracketsTest.java
  k-frontend/src/test/resources/convertor-tests/kore.k
  pyk/regression-new/bison-glr-bug/iele.k
  pyk/src/pyk/kast/outer.py
  pyk/src/tests/integration/test_parse_kast.py
  pyk/src/tests/profiling/test-data/domains.md
  pyk/src/tests/unit/kast/test_kast.py
Labels: automerge

#4300 Fix for `indexed_rewrite` missing rewrite rules
  pyk/src/pyk/kast/manip.py
  pyk/src/tests/integration/test_kprint.py
  pyk/src/tests/unit/kast/test_manip.py
Labels: automerge

#4303 Enable `--no-haskell-binary` by default on macOS
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellBackend.java
  haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellKompileOptions.java
Labels: automerge

#4304 Use release tags for LLVM backend
  .github/workflows/update-deps.yml
  deps/llvm-backend_release
  flake.lock
  flake.nix
Labels: automerge

#4306 Set RTLD_LOCAL via context manager
  pyk/src/pyk/kllvm/importer.py
Labels: automerge

#4305 Renaming satisfiable to valid for `ImpliesResult`
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/pyk/kore/rpc.py
Labels: enhancement, automerge

#4256 Parallel proof exploration
  pyk/src/pyk/kore/rpc.py
  pyk/src/pyk/proof/implies.py
  pyk/src/pyk/proof/proof.py
  pyk/src/pyk/proof/reachability.py
  pyk/src/pyk/testing/__init__.py
  pyk/src/pyk/testing/_kompiler.py
  pyk/src/tests/integration/proof/test_imp.py
  pyk/src/tests/integration/test-data/k-files/imp-simple-spec.k
Labels: automerge, feature

#4296 Add `--kore-rpc-command` option to `pyk prove`
  pyk/src/pyk/cli/pyk.py
Labels: automerge, pyk

#4307 Accept an outer parsed json KAST in kompile
  k-distribution/tests/regression-new/imp-outer-json/Makefile
  k-distribution/tests/regression-new/imp-outer-json/imp.json
  k-frontend/src/main/java/org/kframework/kompile/DefinitionParsing.java
  k-frontend/src/main/java/org/kframework/kompile/KompileOptions.java
  k-frontend/src/main/java/org/kframework/parser/json/JsonParser.java
Labels: automerge

#4288 PyK wrappers for the proof trace python bindings
  pyk/poetry.lock
  pyk/src/pyk/kllvm/compiler.py
  pyk/src/pyk/kllvm/hints/prooftrace.py
  pyk/src/pyk/testing/__init__.py
  pyk/src/pyk/testing/_kompiler.py
  pyk/src/tests/integration/kllvm/test_prooftrace.py
Labels: automerge

#4285 Run `TestImpProve` tests on both backends
  pyk/src/pyk/__main__.py
  pyk/src/pyk/ktool/kprove.py
  pyk/src/tests/integration/ktool/test_imp.py
Labels: automerge, pyk

#4317 Bump version of our Nix tools
  flake.lock
Labels: automerge

#4320 Increase heap size in frontend compiler
  k-distribution/src/main/scripts/lib/checkJava
Labels: automerge

#4322 Add class `Formatter`
  pyk/src/pyk/kast/formatter.py
  pyk/src/tests/integration/kast/__init__.py
  pyk/src/tests/integration/kast/test_formatter.py
  pyk/src/tests/unit/kast/test_formatter.py
Labels: automerge, pyk

#4326 Support NULL return from `requires` binding of `get_requires()`
  pyk/src/pyk/kllvm/utils.py
  pyk/src/tests/integration/kllvm/test_utils.py
Labels: bug, automerge

#4331 Fix flaky un-alias test
  pyk/src/tests/integration/test_kprint.py
Labels: automerge

#4323 Fix main prover in parallel_advance_proof not being closed
  pyk/src/pyk/proof/proof.py
  pyk/src/tests/integration/proof/test_imp.py
Labels: bug, automerge

#4309 Add tests for `kore-rpc` logging options
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/pyk/kcfg/explore.py
  pyk/src/pyk/kore/rpc.py
  pyk/src/tests/integration/kore/test_kore_client.py
Labels: automerge, pyk

#4311 Cell initializers as total functions
  k-frontend/src/main/java/org/kframework/compile/GenerateSentencesFromConfigDecl.java
  k-frontend/src/test/java/org/kframework/compile/GenerateSentencesFromConfigDeclTest.java
  pyk/src/tests/integration/kllvm/test_prooftrace.py
Labels: automerge

#4313 Source and Location attributes for outer parsed modules
  pyk/src/pyk/kast/_ast_to_kast.py
  pyk/src/pyk/kast/att.py
  pyk/src/pyk/kast/outer_parser.py
  pyk/src/pyk/kast/outer_syntax.py
  pyk/src/pyk/kast/utils.py
  pyk/src/tests/unit/kast/test_outer_parser.py
  pyk/src/tests/unit/kast/test_utils.py
  pyk/src/tests/unit/test-data/parse-outer/a.k.expected.json
  pyk/src/tests/unit/test-data/parse-outer/b.k.expected.json
  pyk/src/tests/unit/test-data/parse-outer/c.k.expected.json
  pyk/src/tests/unit/test-data/parse-outer/d.k.expected.json
  pyk/src/tests/unit/test-data/parse-outer/include.k.expected.json
  pyk/src/tests/unit/test-data/parse-outer/markdown.md.expected.json
Labels: automerge

#4327 Add test for proof progressing on reload
  pyk/src/tests/integration/proof/test_imp.py
Labels: bug, automerge

#4339 Fix `import_kllvm` in Pyk and modifying imports in ProofTrace
  pyk/src/pyk/kllvm/hints/prooftrace.py
  pyk/src/pyk/kllvm/importer.py
  pyk/src/tests/integration/kllvm/test_load.py
  pyk/src/tests/integration/kllvm/test_prooftrace.py
Labels: automerge

#4340 pyk RPC: bug-report w/o dt dir
  pyk/src/pyk/kore/rpc.py
Labels: automerge

#4343 Parse attributes `color` and `colors`
  pyk/src/pyk/kast/att.py
  pyk/src/pyk/kast/color.py
  pyk/src/pyk/konvert/_module_to_kore.py
Labels: automerge, pyk, attributes

#4348 Reduce verbosity of the subsumption check message in pyk.proof.reachability
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/pyk/proof/implies.py
  pyk/src/pyk/proof/reachability.py
Labels: automerge

#4350 Enable SimpleSub type inference by default
  k-frontend/src/main/java/org/kframework/parser/inner/ParseInModule.java
Labels: automerge

#4299 Minimizing branching constraints
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/tests/integration/cterm/test_simple.py
  pyk/src/tests/unit/test-data/pyk_toml_test.toml
Labels: enhancement, automerge

#4336 Add textual KAST parser to `pyk`
  pyk/src/pyk/kast/lexer.py
  pyk/src/pyk/kast/parser.py
  pyk/src/tests/unit/kast/test_lexer.py
  pyk/src/tests/unit/kast/test_parser.py
Labels: automerge, pyk

#4334 Parse regular expressions
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/include/kframework/ktest-common.mak
  k-distribution/include/kframework/ktest-fail.mak
  k-distribution/include/kframework/ktest-kdep.mak
  k-distribution/include/kframework/ktest.mak
  k-distribution/k-tutorial/1_basic/03_parsing/README.md
  k-distribution/tests/profiling/avm-semantics/test.k
  k-distribution/tests/profiling/elrond-semantics/test.k
  k-distribution/tests/profiling/wasm-semantics/test.k
  k-distribution/tests/regression-new/checks/checkGroup.k
  k-distribution/tests/regression-new/checks/checkMIntLiteral.k.out
  k-distribution/tests/regression-new/checks/invalidPrec.k.out
  k-distribution/tests/regression-new/imp-outer-json/imp.json
  k-distribution/tests/regression-new/issue-1633/lexical.k
  k-distribution/tests/regression-new/issue-3647-debugTokens/a.test.kast.out
  k-distribution/tests/regression-new/issue-3647-debugTokens/b.test.kast.out
  k-distribution/tests/regression-new/pedanticAttributes/test.k
  k-distribution/tests/regression-new/pedanticAttributes/test.k.out
  k-frontend/src/main/java/org/kframework/definition/regex/Regex.java
  k-frontend/src/main/java/org/kframework/definition/regex/RegexBody.java
  k-frontend/src/main/java/org/kframework/definition/regex/RegexSyntax.java
  k-frontend/src/main/java/org/kframework/kore/convertors/KILtoKORE.java
  k-frontend/src/main/java/org/kframework/parser/inner/kernel/KSyntax2Bison.java
  k-frontend/src/main/java/org/kframework/parser/inner/kernel/Scanner.java
  k-frontend/src/main/java/org/kframework/parser/json/JsonParser.java
  k-frontend/src/main/java/org/kframework/parser/outer/ParseRegex.java
  k-frontend/src/main/java/org/kframework/unparser/ToJson.java
  k-frontend/src/main/scala/org/kframework/definition/Constructors.scala
  k-frontend/src/main/scala/org/kframework/definition/outer-to-string.scala
  k-frontend/src/main/scala/org/kframework/definition/outer.scala
  k-frontend/src/test/java/org/kframework/parser/outer/RegexTest.java
  k-frontend/src/test/scala/org/kframework/definition/OuterTest.scala
  pyk/regression-new/checks/checkGroup.k
  pyk/regression-new/issue-1633/lexical.k
  pyk/regression-new/pedanticAttributes/test.k
  pyk/regression-new/pedanticAttributes/test.k.out
  pyk/src/tests/profiling/test-data/domains.md
Labels: automerge

#4354 More verbose pyk integration tests on CI
  .github/workflows/test-pr.yml
Labels: automerge

#4362 Check lexical identifiers in regular expressions
  k-distribution/tests/regression-new/checks/checkLexicalIdentifiers.k
  k-distribution/tests/regression-new/checks/checkLexicalIdentifiers.k.out
  k-frontend/src/main/java/org/kframework/DirectedGraph.java
  k-frontend/src/main/java/org/kframework/POSet.java
  k-frontend/src/main/java/org/kframework/TopologicalSort.java
  k-frontend/src/main/java/org/kframework/compile/checks/CheckLexicalIdentifiers.java
  k-frontend/src/main/java/org/kframework/definition/regex/RegexSyntax.java
  k-frontend/src/main/java/org/kframework/definition/regex/RegexTransformer.java
  k-frontend/src/main/java/org/kframework/kompile/DefinitionParsing.java
  k-frontend/src/main/java/org/kframework/parser/inner/kernel/Scanner.java
  k-frontend/src/main/java/org/kframework/parser/outer/ParseRegex.java
  k-frontend/src/main/java/org/kframework/utils/errorsystem/KEMException.java
  k-frontend/src/main/scala/org/kframework/compile/ConfigurationInfoFromModule.scala
  k-frontend/src/main/scala/org/kframework/definition/outer-ext.scala
  k-frontend/src/main/scala/org/kframework/definition/outer.scala
Labels: automerge

#4367 Fix incorrect mvnHash value
  flake.nix
Labels: automerge

#4364 Add support for --llvm-mutable-bytes flag to kompile
  pyk/src/pyk/ktool/kompile.py
Labels: automerge

#4342 kompilex command for pyk
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cli/args.py
  pyk/src/pyk/cli/pyk.py
  pyk/src/pyk/kast/att.py
  pyk/src/pyk/kast/outer.py
  pyk/src/pyk/kast/pretty.py
  pyk/src/pyk/ktool/kompile.py
  pyk/src/tests/integration/test-data/prelude-modules.json
  pyk/src/tests/integration/test_pyk.py
Labels: automerge

#4373 Run homebrew release on macOS 14 / arm64
  .github/workflows/release.yml
Labels: automerge

#4365 Support Unicode-aware regex
  k-distribution/tests/regression-new/checks/checkRegexRanges.k
  k-distribution/tests/regression-new/checks/checkRegexRanges.k.out
  k-distribution/tests/regression-new/checks/checkRegexUnicode.k
  k-distribution/tests/regression-new/checks/checkRegexUnicode.k.out
  k-distribution/tests/regression-new/regex-unicode/1.test
  k-distribution/tests/regression-new/regex-unicode/1.test.out
  k-distribution/tests/regression-new/regex-unicode/Makefile
  k-distribution/tests/regression-new/regex-unicode/test.k
  k-frontend/src/main/java/org/kframework/compile/checks/CheckLexicalIdentifiers.java
  k-frontend/src/main/java/org/kframework/compile/checks/CheckRegex.java
  k-frontend/src/main/java/org/kframework/definition/regex/RegexBody.java
  k-frontend/src/main/java/org/kframework/definition/regex/RegexSyntax.java
  k-frontend/src/main/java/org/kframework/definition/regex/RegexTransformer.java
  k-frontend/src/main/java/org/kframework/definition/regex/RegexVisitor.java
  k-frontend/src/main/java/org/kframework/kompile/DefinitionParsing.java
  k-frontend/src/main/java/org/kframework/parser/outer/ParseRegex.java
Labels: automerge

#4345 Add support for parallel Booster kompilation
  pyk/src/pyk/ktool/kompile.py
  pyk/src/tests/integration/test_kompile.py
Labels: automerge, pyk

#4361 Remove `flatten_label` recursion
  pyk/src/pyk/kast/inner.py
  pyk/src/tests/unit/kast/test_inner.py
Labels: enhancement, automerge

#4381 Fix typo when compiling regex ranges
  k-distribution/tests/regression-new/issue-4380-regex-range/1.test
  k-distribution/tests/regression-new/issue-4380-regex-range/1.test.out
  k-distribution/tests/regression-new/issue-4380-regex-range/2.test
  k-distribution/tests/regression-new/issue-4380-regex-range/2.test.out
  k-distribution/tests/regression-new/issue-4380-regex-range/3.test
  k-distribution/tests/regression-new/issue-4380-regex-range/3.test.out
  k-distribution/tests/regression-new/issue-4380-regex-range/4.test
  k-distribution/tests/regression-new/issue-4380-regex-range/4.test.out
  k-distribution/tests/regression-new/issue-4380-regex-range/5.test
  k-distribution/tests/regression-new/issue-4380-regex-range/5.test.out
  k-distribution/tests/regression-new/issue-4380-regex-range/6.test
  k-distribution/tests/regression-new/issue-4380-regex-range/6.test.out
  k-distribution/tests/regression-new/issue-4380-regex-range/Makefile
  k-distribution/tests/regression-new/issue-4380-regex-range/regex.k
  k-frontend/src/main/java/org/kframework/definition/regex/RegexTransformer.java
Labels: automerge

#4387 Build and start to deploy pyk documentation
  .github/workflows/release.yml
Labels: automerge

#4389 Install Python 3.10 in `gh-pages` job
  .github/workflows/release.yml
Labels: automerge

#4392 Exclude the `pyk` directory from Jekyll conversion
  _config.yml
Labels: automerge

#4394 Bypass Jekyll on GitHub Pages
  _config.yml
  web/public_content/.nojekyll
Labels: automerge

#4395 Create `.nojekyll` dynamically
  .github/workflows/release.yml
  web/public_content/.nojekyll
Labels: automerge

#4396 Including `compute_ordinals` and `get_axiom_by_ordinal` in Pyk `kore.Definition`
  pyk/src/pyk/kore/syntax.py
Labels: automerge, pyk

#4385 emit cell attribute into kore definition
  k-distribution/tests/regression-new/map-symbolic-tests-haskell/assignment-11-spec.k
  k-distribution/tests/regression-new/map-symbolic-tests-haskell/assignment-11-spec.k.out
  k-frontend/src/main/scala/org/kframework/attributes/Att.scala
  pyk/src/pyk/konvert/_module_to_kore.py
Labels: automerge

#4402 Minor cleanups to prover, kast
  pyk/src/pyk/kast/manip.py
  pyk/src/pyk/kast/outer.py
  pyk/src/pyk/kast/rewrite.py
  pyk/src/pyk/ktool/kprove.py
Labels: automerge

#4405 add --proof-hint flag to krun
  k-distribution/src/main/scripts/bin/krun
  k-distribution/tests/regression-new/proof-instrumentation/Makefile
  k-distribution/tests/regression-new/proof-instrumentation/input.test
  k-distribution/tests/regression-new/proof-instrumentation/input.test.out
Labels: automerge

#4397 Update links to pyk API docs
  pyk/README.md
  web/pages/index.md
Labels: automerge

#4403 Improve parsing of variables in pyk KAST parser
  pyk/src/pyk/kast/lexer.py
  pyk/src/pyk/kast/parser.py
  pyk/src/tests/unit/kast/test_lexer.py
  pyk/src/tests/unit/kast/test_parser.py
Labels: automerge, pyk
