Repository runtimeverification/k, pull requests merged in 2024-07, with the labels that each got.

#4487 Inline `app` in `Assoc`
  pyk/src/pyk/kllvm/convert.py
  pyk/src/pyk/kore/manip.py
  pyk/src/pyk/kore/match.py
  pyk/src/pyk/kore/parser.py
  pyk/src/pyk/kore/prelude.py
  pyk/src/pyk/kore/syntax.py
  pyk/src/pyk/ktool/kfuzz.py
  pyk/src/tests/integration/ktool/test_fuzz.py
  pyk/src/tests/unit/kore/test_ml_pattern.py
Labels: automerge

#4494 Use portable sed invocation
  k-distribution/include/kframework/ktest-common.mak
Labels: automerge

#4492 Pyk: Wrap fuzzing in an interface
  pyk/src/pyk/ktool/kfuzz.py
  pyk/src/tests/integration/ktool/test_fuzz.py
Labels: automerge

#4045 Deprecate `symbol` and `klabel`
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/include/kframework/builtin/ffi.md
  k-distribution/include/kframework/builtin/json.md
  k-distribution/include/kframework/builtin/kast.md
  k-distribution/include/kframework/builtin/rat.md
  k-distribution/tests/regression-new/bison-glr-bug/iele.k
  k-distribution/tests/regression-new/checkWarns/missingKlabel.k
  k-distribution/tests/regression-new/checkWarns/symbolKLabel.k
  k-distribution/tests/regression-new/checkWarns/symbolKLabel.k.out
  k-distribution/tests/regression-new/checks/invalidSymbol.k
  k-distribution/tests/regression-new/checks/invalidSymbol.k.out
  k-distribution/tests/regression-new/checks/overloadKLabel.k.out
  k-distribution/tests/regression-new/checks/paramAmb.k.out
  k-distribution/tests/regression-new/context-alias-2/test.k
  k-distribution/tests/regression-new/context-labels/context-spec.k.out
  k-distribution/tests/regression-new/context-labels/context.k
  k-distribution/tests/regression-new/issue-1263/test.k
  k-distribution/tests/regression-new/issue-1273/test.k
  k-distribution/tests/regression-new/issue-1682-korePrettyPrint/test.k
  k-distribution/tests/regression-new/issue-1760/test.k
  k-distribution/tests/regression-new/issue-1760/test.k.out
  k-distribution/tests/regression-new/issue-1879-kproveTrans/haskell/test.k
  k-distribution/tests/regression-new/issue-2321-kprovexCrash/test.k
  k-distribution/tests/regression-new/issue-999/kat.k
  k-distribution/tests/regression-new/issue-999/kat.k.out
  k-distribution/tests/regression-new/pl-tutorial/2_languages/2_kool/2_typed/2_static/kool-typed-static.md
  k-distribution/tests/regression-new/proof-instrumentation-debug/input.test.out
  k-distribution/tests/regression-new/proof-instrumentation/input.test.out
  k-distribution/tests/regression-new/unparseKORE/test.k
  k-frontend/src/main/java/org/kframework/compile/checks/CheckAtt.java
  pyk/regression-new/bison-glr-bug/iele.k
  pyk/regression-new/checkWarns/missingKlabel.k
  pyk/regression-new/issue-1273/test.k
  pyk/regression-new/issue-1760/test.k
  pyk/regression-new/issue-1760/test.k.out
  pyk/regression-new/issue-1879-kproveTrans/haskell/test.k
  pyk/regression-new/issue-999/kat.k
  pyk/regression-new/issue-999/kat.k.out
  pyk/regression-new/unparseKORE/test.k
  pyk/src/pyk/konvert/_module_to_kore.py
  pyk/src/tests/integration/test_kompile.py
Labels: automerge

#4509 Bug report sequence storage changes
  pyk/src/pyk/kore/rpc.py
  pyk/src/pyk/utils.py
Labels: automerge

#4506 Remove `Atts.KLABEL`
  pyk/src/pyk/kast/att.py
  pyk/src/pyk/kast/pretty.py
  pyk/src/pyk/kore_exec_covr/__main__.py
  pyk/src/tests/unit/kast/test_att.py
Labels: automerge

#4493 Prune follows for K flake
  flake.lock
  flake.nix
Labels: automerge

#4510 Do not print from `kompile` by default
  pyk/src/pyk/__main__.py
  pyk/src/pyk/krepl/repl.py
  pyk/src/pyk/ktool/kompile.py
  pyk/src/pyk/ktool/kprint.py
  pyk/src/pyk/ktool/kprove.py
  pyk/src/pyk/ktool/krun.py
Labels: automerge, pyk

#4512 [adopt: #4504] README: Add libunwind-dev to list of dependencies for Debian
  README.md
Labels: automerge

#4500 Nix refactoring
  .github/workflows/test-pr.yml
  flake.lock
  flake.nix
  nix/pyk-overlay.nix
  pyk/flake.nix
Labels: automerge

#4514 fix llvm-kompile being passed more options conventionally
  llvm-backend/src/main/java/org/kframework/backend/llvm/LLVMBackend.java
Labels: automerge

#4518 Set logging level to `DEBUG` for `llvm_interpret_raw`
  pyk/src/pyk/ktool/krun.py
  pyk/src/pyk/utils.py
Labels: automerge

#4520 Allow log origin "proxy"
  pyk/src/pyk/kore/rpc.py
Labels: automerge

#4242 Expose function evaluation from KLLVM bindings
  pyk/src/pyk/kllvm/runtime.py
  pyk/src/tests/integration/kllvm/test_evaluate.py
Labels: automerge, pyk

#4522 mark Int2Bytes(Int,Endianness,Signedness) rules as preserving definedness
  k-distribution/include/kframework/builtin/domains.md
Labels: automerge

#4525 Test no-secret PR workflow
  .github/workflows/test-pr.yml
Labels: automerge

#4511 Add class `ClaimLoader`
  pyk/src/pyk/kast/markdown.py
  pyk/src/pyk/kast/utils.py
  pyk/src/pyk/ktool/claim_loader.py
  pyk/src/pyk/ktool/utils.py
  pyk/src/pyk/utils.py
Labels: automerge

#4524 Make request IDs unique across clients
  pyk/src/pyk/kore/rpc.py
Labels: automerge

#4530 Fix attribute parsing
  pyk/src/pyk/kast/outer_parser.py
  pyk/src/tests/unit/kast/test_outer_parser.py
Labels: automerge, pyk

#4535 Removing example of relative position as Napoleon can't render it properly
  pyk/src/pyk/kllvm/hints/prooftrace.py
Labels: automerge, documentation

#4531 Fix crash with failure info with custom multiplicity cells
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/tests/integration/proof/test_mini_kevm.py
Labels: automerge

#4533 Further fine-tune `Int2Bytes(Int, Endianness, Signedness)` equations for booster
  k-distribution/include/kframework/builtin/domains.md
Labels: automerge

#4544 Resolve non-determinism in minInt
  k-distribution/include/kframework/builtin/domains.md
Labels: automerge

#4505 install-build-deps script
  README.md
  install-build-deps
Labels: automerge

#4548 Use `gnu` tar format for the bug reports
  pyk/src/pyk/utils.py
Labels: automerge

#4554 HOTFIX define Int2Bytes for -1 again
  k-distribution/include/kframework/builtin/domains.md
  k-distribution/tests/regression-new/int2bytes-no-len/0.test
  k-distribution/tests/regression-new/int2bytes-no-len/0.test.out
  k-distribution/tests/regression-new/int2bytes-no-len/1.test
  k-distribution/tests/regression-new/int2bytes-no-len/1.test.out
  k-distribution/tests/regression-new/int2bytes-no-len/10.test
  k-distribution/tests/regression-new/int2bytes-no-len/10.test.out
  k-distribution/tests/regression-new/int2bytes-no-len/11.test
  k-distribution/tests/regression-new/int2bytes-no-len/11.test.out
  k-distribution/tests/regression-new/int2bytes-no-len/12.test
  k-distribution/tests/regression-new/int2bytes-no-len/12.test.out
  k-distribution/tests/regression-new/int2bytes-no-len/13.test
  k-distribution/tests/regression-new/int2bytes-no-len/13.test.out
  k-distribution/tests/regression-new/int2bytes-no-len/14.test
  k-distribution/tests/regression-new/int2bytes-no-len/14.test.out
  k-distribution/tests/regression-new/int2bytes-no-len/2.test
  k-distribution/tests/regression-new/int2bytes-no-len/2.test.out
  k-distribution/tests/regression-new/int2bytes-no-len/3.test
  k-distribution/tests/regression-new/int2bytes-no-len/3.test.out
  k-distribution/tests/regression-new/int2bytes-no-len/4.test
  k-distribution/tests/regression-new/int2bytes-no-len/4.test.out
  k-distribution/tests/regression-new/int2bytes-no-len/Makefile
  k-distribution/tests/regression-new/int2bytes-no-len/test.k
Labels: automerge

#4550 Fix typo in README
  README.md
Labels: automerge

#4556 Remove references to my contact details from K repo
  CODEOWNERS
  CONTRIBUTING.md
  package/debian/kframework-frontend/changelog
  package/debian/kframework-frontend/control.jammy
  package/debian/kframework-frontend/copyright
Labels: automerge

#4560 Add extra check for lldb path in krun --debugger
  k-distribution/src/main/scripts/bin/krun
Labels: automerge

#4561 Status bar support in proof loop
  pyk/src/pyk/proof/proof.py
  pyk/src/pyk/proof/reachability.py
Labels: enhancement, automerge
