Repository runtimeverification/k, pull requests merged in 2025-03, with the labels that each got.

#4766 Add Lean prelude instances and change collection implementation
  pyk/src/pyk/klean/k2lean4.py
  pyk/src/pyk/klean/template/{{ cookiecutter.package_name }}/{{ cookiecutter.library_name }}/Prelude.lean
Labels: automerge, lean4-backend

#4768 Add support for generating `deriving` clause
  pyk/src/pyk/klean/README.md
  pyk/src/pyk/klean/__main__.py
  pyk/src/pyk/klean/generate.py
  pyk/src/pyk/klean/k2lean4.py
  pyk/src/pyk/klean/model.py
  pyk/src/tests/integration/klean/test_generate.py
Labels: automerge, lean4-backend

#4767 Update Poetry version
  .github/actions/setup-pyk-env/action.yml
  .github/actions/with-k-docker/Dockerfile
  .github/workflows/release.yml
  pyk/poetry.lock
  pyk/regression-new/include/ktest-fail.mak
  pyk/regression-new/include/ktest.mak
Labels: automerge

#4757 Process complex LHS patterns in function rules
  pyk/poetry.lock
  pyk/pyproject.toml
  pyk/src/pyk/klean/k2lean4.py
  pyk/src/pyk/klean/template/{{ cookiecutter.package_name }}/{{ cookiecutter.library_name }}/Prelude.lean
  pyk/src/pyk/kore/syntax.py
Labels: automerge, lean4-backend

#4769 Use `bottom_up` in fuzzer template substitution
  pyk/src/pyk/ktool/kfuzz.py
Labels: automerge

#4771 Refactor adding modules via `CTermSymbolic`
  pyk/src/pyk/cterm/symbolic.py
  pyk/src/pyk/proof/reachability.py
Labels: automerge

#4773 Check for empty output in `llvm_interpret`
  pyk/src/pyk/ktool/krun.py
  pyk/src/tests/integration/test_krun.py
Labels: automerge, pyk

#4770 `Prelude.lean`: embed carrier implementation in hook signatures
  pyk/src/pyk/klean/template/{{ cookiecutter.package_name }}/{{ cookiecutter.library_name }}/Prelude.lean
Labels: automerge, lean4-backend

#4746 Update `pyk` dependencies
  nix/pyk-overlay.nix
  nix/resources/attrs-pyproject.toml.patch
  pyk/poetry.lock
  pyk/src/pyk/kast/_ast_to_kast.py
  pyk/src/pyk/kllvm/hints/prooftrace.py
  pyk/src/pyk/kore_exec_covr/kore_exec_covr.py
  pyk/src/tests/integration/proof/test_imp.py
Labels: automerge, pyk

#4775 PyK: Misc enhancements to KCFG and anti-unification
  pyk/src/pyk/cterm/cterm.py
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/pyk/kcfg/show.py
Labels: automerge

#4772 Allow introducing semantic rules in kprove
  k-frontend/src/main/java/org/kframework/kompile/Kompile.java
  k-frontend/src/main/java/org/kframework/kprove/KProveOptions.java
  k-frontend/src/main/java/org/kframework/kprove/ProofDefinitionBuilder.java
  pyk/src/pyk/ktool/kprove.py
  pyk/src/tests/integration/test-data/k-files/looping-spec.k
Labels: automerge
