Repository runtimeverification/k, pull requests merged in 2025-05, with the labels that each got.

#4809 Factor out helper for printing CSubst in KCFGShow
  pyk/src/pyk/kcfg/tui.py
Labels: automerge

#4810 Move module `prove_rpc` from `ktool` to `proof`
  pyk/src/pyk/__main__.py
  pyk/src/pyk/proof/prove_rpc.py
  pyk/src/tests/integration/proof/test_prove_rpc.py
Labels: automerge, pyk

#4812 Use relative imports inside the pyk library
  pyk/src/pyk/kcfg/exploration.py
  pyk/src/pyk/kcfg/kcfg.py
  pyk/src/pyk/kcfg/minimize.py
  pyk/src/pyk/kdist/__main__.py
  pyk/src/pyk/kdist/utils.py
  pyk/src/pyk/klean/__main__.py
  pyk/src/pyk/proof/reachability.py
  pyk/src/pyk/testing/_kompiler.py
Labels: automerge

#4811 Remove unused private attribute from `KProve`
  pyk/src/pyk/ktool/kprove.py
Labels: automerge, pyk

#4819 Small changes in preparation for CTermShow
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cli/pyk.py
  pyk/src/pyk/cterm/cterm.py
  pyk/src/pyk/kast/manip.py
  pyk/src/pyk/kcfg/show.py
  pyk/src/tests/unit/kast/test_manip.py
Labels: automerge

#4820 Add Maven informational lock file and make Maven build more replicable
  flake.nix
  mvn-lock/dependencies-lock.json
  mvn-lock/haskell-backend/dependencies-lock.json
  mvn-lock/k-distribution/dependencies-lock.json
  mvn-lock/k-frontend/dependencies-lock.json
  mvn-lock/llvm-backend/dependencies-lock.json
  mvn-lock/llvm-backend/src/main/native/llvm-backend/matching/dependencies-lock.json
  nix/build-maven-package.nix
  nix/k.nix
  nix/resources/maven-metadata-central-replacements/GSON.xml
  pom.xml
  scripts/update-maven-locks.sh
Labels: automerge

#4808 Factor out CTermShow class for simpler node printing
  pyk/src/pyk/__main__.py
  pyk/src/pyk/cterm/show.py
  pyk/src/pyk/kcfg/show.py
  pyk/src/pyk/kcfg/tui.py
  pyk/src/pyk/proof/show.py
  pyk/src/pyk/proof/tui.py
  pyk/src/tests/integration/proof/test_cell_map.py
  pyk/src/tests/integration/proof/test_custom_step.py
  pyk/src/tests/integration/proof/test_goto.py
  pyk/src/tests/integration/proof/test_imp.py
  pyk/src/tests/integration/proof/test_mini_kevm.py
  pyk/src/tests/integration/proof/test_non_det.py
  pyk/src/tests/unit/kcfg/test_minimize.py
  pyk/src/tests/unit/mock_kprint.py
  pyk/src/tests/unit/test_kcfg.py
Labels: automerge

#4821 Document definedness condition for `substrBytes`
  k-distribution/include/kframework/builtin/domains.md
Labels: automerge

#4823 `Prelude.lean`: fix error on the length of `Array.?pad`
  pyk/src/pyk/klean/template/{{ cookiecutter.package_name }}/{{ cookiecutter.library_name }}/Prelude.lean
Labels: automerge, lean4-backend

#4827 Lean 4 backend: further function implementation (2)
  pyk/src/pyk/klean/k2lean4.py
  pyk/src/pyk/klean/template/{{ cookiecutter.package_name }}/{{ cookiecutter.library_name }}/Prelude.lean
Labels: automerge, lean4-backend
